### ISSUE TITLE
Migrate from kohana to laravel / lumen

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1372]
This will probably be a multi step process

1. Install laravel, and migrate routing to laravel. All validation, db queries still use Kohana. Use both auto loaders side-by-side. The big lift here is just migrating the Rest controller.
2. Start migrating away from any helpers etc we're using. Try to avoid auto loading anything from kohana. DB and validation code could still use kohana.. but we should try to rely on *just* those libraries and nothing else
3. Migrate validators
4. Finally migrate DB code.

**Comment by rjmackay** [comment]
@jshorland This got slightly more urgent now Kohana is taking everything offline as of July http://discourse.kohanaframework.org/t/kohana-retirement-2017-07-01/1277

**Comment by rjmackay** [comment]
**Progress**

- [x] Add lumen in to codebase #1663
- [ ] Migrate API controllers to Lumen #1674 
- [ ] Move Repos, Validators, etc out of Kohana
- [ ] Move DI set up out of Kohana (into a service provider)
- [ ] Remove Kohana dependencies from everything other than validators and repos
- [ ] Stop bootstrapping kohana
- [ ] Fix Dataprovider callbacks
- [ ] Migrate event handling/listeners to lumen
- [ ] Migrate console to artisan
- [ ] Make `artisan migrate` call phinx
- [ ] Migrate validators to use lumen
  - Add test coverage
  - Use Illuminate\Validation
- [ ] Migrate repos
  - Do we refactor too?
  - Or just move to Illuminate\Database

**Comment by rjmackay** [comment]
Looking at the kohana code. I think it might be possible to extract just the Kohana Validation libs into their own library while we transition, and removing the Kohana dependencies from the database lib should be fairly simple too.

**Comment by rjmackay** [comment]
@willdoran here's where this is at:

- I'm working on splitting Kohana's Validation lib into a standalone (https://github.com/ushahidi/kohana-validation)...
- Next things are
   - Move dataproviders into namespaces ie. src/App/DataProviders. I suggesting *just* moving the code and namespacing it. *Don't* refactor, we will do that, but first we want to drop kohana. The fastest way to do that is to get the dataprovider code out of modules.
   - Remove kohana dependencies from ohanzee/database & namespace it. You can see Woody started namespacing it over here: https://github.com/ushahidi/ohanzee-db/compare/master...namespaces
    We'll also need to move our custom mysqli database code into our fork too https://github.com/ushahidi/platform/tree/lumen/application/classes/Database
    The main dependency on Kohana is just using its config loading, thats easy to drop.
- Once we do that I think we can loading Kohana Core at all

**Comment by samtheson** [comment]
@rjmackay Hey I hadn't seen this one. I :heart: it!

Let me know if I can help in any way. Laravel is a daily eatz for me in several production environments. I'm sure I can make room of at least 4 or 5 hours for you each week.

**Comment by caharding** [comment]
@rjmackay can you break this out into you'd like to accomplish this cycle

**Comment by rjmackay** [comment]
Outstanding questions (leaving this for myself):
- [ ] Should I change `httpdocs` to `public` to match the standard laravel convention?
- [ ] Can I replace artisan migrate with phinx?

**Comment by rjmackay** [comment]
@tuxpiper to make migrations easy I think I'll keep the using `httpdocs` directory. However to follow the lumen conventions I might symlink `public` to httpdocs. Does that sound reasonable?

**Comment by rjmackay** [comment]
This is now primarily just waiting for QA

**Comment by tuxpiper** [comment]
@rjmackay that sounds totally reasonable to me. I've approved in the PR
