### ISSUE TITLE
A user's to-do list in a deployment

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1383]
User stories:
- [ ] As any user, I want to see all tasks assigned to me
- [ ] As any user, I want to see an overview of all tasks in their various stages
- [ ] As a user with manage tasks permission, I want an option to see ALL tasks
- [ ] As any user, I want to see all unassigned tasks
- [ ] As any user, I want to be able to complete my tasks from my task list
  *QUESTION: what happens if there’s changes to the original post as a result of the accomplishing of the task? For example, a verification actually results in adding a new field to the original post.
- [ ] As any user, I want to filter my task list by type of task
- [ ] As any user, I want to sort my task list by post creation date 
- [ ] As any user, I want to sort my task list by recently edited

Aha! Link: https://ushahiditeam.aha.io/features/PROD-670

**Comment by brandonrosage** [comment]
This is provided by the "Tasks" mode:

![Tasks mode](https://cloud.githubusercontent.com/assets/1136279/20284199/c5507542-aa81-11e6-8f12-4749facb8f56.png)

By default, this mode displays all posts that have incomplete tasks assigned to you. Its toolbox includes controls for configuring how the posts are sorted, and showing tasks based on who they're assigned to, whether they're complete, and/or whether their post is published, under review, or archived.

When you select a task's name, it reveals the task's detailed modal window. You can optionally access quick actions from the "---" action trigger. Tasks that can be completed without first filling out task-specific fields will reveal the option to "Mark complete."

![action menu](https://cloud.githubusercontent.com/assets/1136279/20284299/1ee61fee-aa82-11e6-92f8-5850aef9c429.png)

If it requires fields be completed, however, the option to mark the task complete is not available. 

Sorting and task-specific filtering can be done in both the toolbox and "Filters" control.

**Comment by brandonrosage** [comment]
@jshorland + @caharding + @rjmackay: This is one of four issues that combine to define the next iteration of "Tasks" for Ushahidi. Those four issues include #1381, #1382, #1383, and #1385.

Though they may not be actively developed in the near term, I'd really like to jump on iterating and testing many of the decisions and assumptions here. So your timely feedback and questions are appreciated. Thanks.

**Comment by rjmackay** [comment]
This looks good to me. 

One aside: Is there an issue for adding data source filters to the mode-context? And is there an issue to track turning data source posts (ie. SMS/Twitter messages) into their own pseudo survey? .. I see both of these implied in Tasks, so it would be good to track them as dependencies or at least related issues.

**Comment by brandonrosage** [comment]
@jshorland, @aoduor: I have a handful of wireframes I want to use to solicit feedback from existing users who can help steer us toward the right mental model for presenting pending tasks. **Who can I ask to connect me with four to eight willing participants?**

As I see it, we're asking these folks for 20 minutes of their time (ideally, within my working hours) to join me (and other Ushahidi folks, if they want to observe) on a Google Hangout or WebEx, where we'd ask them a few questions about "workflow" and share my screen in order to use the wireframes as a conversation piece. It's possible that we'd revise or create new wireframes in real-time, on the calls, to respond to their feedback.

Participants would not be asked to share their video or screen.

**Comment by brandonrosage** [comment]
[I've staged an outline for the user test ](https://docs.google.com/a/ushahidi.com/document/d/1g054jelY7PcabE0zQOb22E1hNLFDSwXRoqeXwg_8m-s/edit?usp=sharing)I intend to facilitate this month, with a summary of the plan, questions, and an empty space for a list of the participants ;)

**Comment by aoduor** [comment]
@brandonrosage i can help identify groups of users to include in this study. 

Clarifying question: These would be existing users of current version of platform using tasks currently, yes?

**Comment by brandonrosage** [comment]
@aoduor: The user test intentionally avoids discussing "Tasks" as a feature in its existing form. So it's not terribly important that the participants be able to speak to their experience with it. Participant requirements would just be, A, that they are Ushahidi deployers, and B, that they're willing to jump on a video conference to talk and offer feedback on some wireframes.

Past that, a bonus (but not requirement) would be that they're v3 users.

**Comment by aoduor** [comment]
Hey @brandonrosage, i've got a solid list of potential users to run this test with. 

I'm trying to draft messaging to request their participation. Please let me know proposed dates and times you'd like to host the test :)

**Comment by brandonrosage** [comment]
@aoduor: If necessary, I can do some middle-of-the-night interviews. Otherwise, my preference is any of the following times and dates:

- **Monday, Feb. 13**: 8:30 a.m. to 5 p.m. CT
- **Tuesday, Feb. 14**: 10 a.m. to 2 p.m. CT
- **Wednesday, Feb. 15**: 8:30 a.m. to 5 p.m. CT
- **Thursday, Feb. 16**: 8:30 a.m. to 5 p.m. CT
- **Friday, Feb. 17**: 8:30 a.m. to 5 p.m. CT
- **Monday, Feb. 20**: 8:30 a.m. to 5 p.m. CT
- **Tuesday, Feb. 21**: 10 a.m. to 2 p.m. CT
- **Wednesday, Feb. 22**: 8:30 a.m. to 3 p.m. CT
- **Friday, Feb. 24**: 9 a.m. to 5 p.m. CT

**Comment by aoduor** [comment]
Alrighty, [let me know if this is all good](https://docs.google.com/document/d/1WT5ALXGt1u8pi3JrXLhkv4rdYQRtCuITIxlgLNHGjRk/edit#) and i'll send these out to the list of participants i drafted

**Comment by aoduor** [comment]
@brandonrosage this is set in motion, and we've already got some of these getting scheduled for this week.

**fistbump**

**Comment by brandonrosage** [comment]
For review by @jshorland, @caharding, and @nat:

Below is my proposed solution to this particular slice of the overall "Tasks" epic, starting with the definition of a task within Ushahidi:

> An explicit indication that a field (or group of fields) needs to be completed; by a specific person or group of people.

By assigning a field to someone (or "anybody"), you've created a task. To see your "to-do list," you simply select "Tasks" mode from the mode bar:

![Tasks](https://cloud.githubusercontent.com/assets/1136279/25449783/7bf06e1c-2a82-11e7-89bc-4aa745d4ffc8.png)

By default, it displays incomplete tasks assigned to you. Each task is displayed within the postcard for the survey response it's attached to. They're named for the specific field they're attached to and include a striped "under construction" visual indicator to their left.

Each postcard displays the response's status and submitted date. The attached task has an "..." action button appended to it, which reveals the ability to change its assignee or remove it all together.

![postcard](https://cloud.githubusercontent.com/assets/1136279/25449929/f65c7eac-2a82-11e7-88f0-190d7e61fb29.png)

These actions are also accessible as bulk actions, along with "Mark as" (incomplete or complete), when selecting one or more postcards from the list.

![listing toolbar](https://cloud.githubusercontent.com/assets/1136279/25450053/58db5bf2-2a83-11e7-9907-a263ab1eecfc.png)

The "Tasks" mode's filters (either in the toolbox or "Filters" modal window) include:
* Assignee (includes "anybody")
* Task status (incomplete or complete)
* Stage (synonym for "Status")
* Date (same available configurations as in any mode)

### NOTES

> As any user, I want to see an overview of all tasks in their various stages

As discussed at length April 20 in the SF Hit Team review, tasks do not belong to stages. Responses do. So when you filter by "Stage" in Tasks mode, you can see tasks in any given combination of stages.

> As any user, I want to filter my task list by type of task

This is not yet addressed, but it is considered. Recall that the SF Hit Team review yielded the suggestion that we re-use the 'survey filters' pattern's nested "categories" convention to display each of its field names that have tasks attached to them. This still needs some work and vetting. I'm not certain this is the right way to provide that filter. But we'll give it a try.

**Comment by caharding** [comment]
Looks good. Two requests:
1. More information density. 
2. Some way to see all the tasks that need completion associated with a survey like the note you made at the bottom of your last comment
