### ISSUE TITLE
Election Facebook bot Epic

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1702]
Facebook is partenred with Ushahidi to help create a FB bot data source for the Kenyan election. Most people are on FB messenger, we should be there too. 

## Use cases and User flow

1. Simple Bot
- [x] User is told they can report election violation via a bot
- [x] User can connect to a bot that points them to Uchaguzi
- [x] User can go to Uchaguzi FB page where the bot will pop up

2. Report Bot
- [x] User can submit their report via bot
- [x] User can submit a report and image
- [x] User is notified that their report is received
- [x] Report is filed on Ushahidi server
- [ ] User can submit video 

3. Sharing & Language
- [ ] Bot auto detects language in En or Sw
- [ ] User can switch language in menu
- [x] User can share chat bot with others in conversation via [Chat Extensions]
- [ ] User is asked to share that they voted (link to share on FB)

OUT OF SCOPE
~~4. Register Bot~~
~~- User can get vote registration information~~
~~- User is reminded to register~~

STRETCH GOAL
5. Polling Bot
- [ ] User can check polling location before election (requires polling loco data)
- [ ] User is alerted of polling location on voting day
 (https://developers.facebook.com/docs/messenger-platform/guides/chat-extensions), so the bot can be added into 1:1 or multi-person discussions

**Comment by caharding** [comment]
User can get info to register to vote X time before election (req partner with reg)
User is reminded to register
User can check polling location before election (requires polling loco data)
User is alerted of polling location on voting day
User is asked to share that they voted  (link to share on FB)
User is alerted they can report on violations (
User can submit a report and image/video
User is notified that their report is received 
Bot is shared by FB on election news feed promotions for reporting incidents

**Comment by willdoran** [comment]
@caharding @rjmackay @jshorland 

## Preamble
- FB bots are connected to businesses/orgs, it's a 1:1 relationship so any bot would have to be specific to a Kenyan Election Facebook entity rather than Ushahidi's own page
- The bot can be accessed in the following ways:
  - Directly from Facebook page
  - Through facebook search
  - Through adding as a contact on messenger
  - Through Messenger Codes/Paramteric Codes (basically QR)
  - Via Messenger Buttons embed directly on websites
  - Messenger Links
  - By clicking on an advertisement
  - Customer Matching, this uses phone numbers to allow you to add your customers over facebook, facebook collects phone numbers via their phone app - it's a key part of how they suggest friends on facebook
- The Bot can interpret natural language as structured data
- It can also expand its semantic lexicon through exposure to users and the outcomes of the requests they make; on the job training essentially
- [wit.ai](https://wit.ai/) is the group that provides the natural language processing and are also a data analysis company. They are owned by facebook and provide their tool and service for free.
- Bots have the following 3 core elements:
  1. Send/Receive API, this includes, text, image and "calls to action"(CTAs) 
  2. Generic Message Templates, these are outline templates that essentially demonstrate usecases
  3. Welcome Screen, start point, including beginning point CTA - what is the app, what does the user do next
- Facebook's bot 'M' is what is called an human/bot hybrid, the bot answers basic questions but as soon as it get's stuck it routes queries to normal support agents. **So it's important to consider that the bot will fail at some point and will need to be backed up by some access to humans**

**- All bots go through APP review, this is likely to take a significant amount of time even if they "help" us so should be accounted for/talked about up front. This is probably the main reason features would have to be reduced**


## Usecases and User flow
- [ ] Enumerate Usecases and User flow
  - [ ] User can get vote registration information
    -  [The Independent Electoral Boundaries Commission]() provides [historical voter data](http://vote.iebc.or.ke/) and a mechanism for individuals to check if they are still [registered](http://vote.iebc.or.ke) and a pending new [method](https://www.iebc.or.ke/registration/?check)
    - [Go Vote Kenya](https://kenya.gottovote.cc/) provides both registration location data and a means to check that you are registered or if someone else is registered in your name
    - Registration status/confirmation can also be done by SMS shortcode
    - Not sure how kosher it is that these sites ask individuals to provide passport/identity numbers
- [ ] User is reminded to register
  - Through [account linking](https://developers.facebook.com/docs/messenger-platform/account-linking) we can auth users and indeed register them with the platform
  - [Messenger Conversation Ads](https://developers.facebook.com/docs/messenger-platform/guides/ads) would probably be the most effective way to do this, as when the user clicks on an add it will open our bot(assuming FB gives us free advertising space)
- [ ] User can check polling location before election (requires polling loco data)
  - If user enters a query about polling and a location, we could make a request to a 3rd party source and return the data through the bot
- [ ] User is alerted of polling location on voting day
  - Requires either: 
    - user to provide us with some information/account link
    - target add
    - User asks the bot and we return queried info
- [ ] User is asked to share that they voted (link to share on FB)
  - There are a number of ways to do this:
    - Targeted add
    - Broadcast message to those already talking to the bot, CTAs
    - Bot can just bring it up awkwardly in conversation and they can share from there
- [ ] User is alerted they can report on violations 
  - We can take response to questions and rich data, this can be passed by to the platform
- [ ] User can submit a report and image/video
  - same as previous
- [ ] User is notified that their report is received
  - We can even return a link to the platform, if their post is published
- [ ] User can share chat bot with others in conversation via [Chat Extensions](https://developers.facebook.com/docs/messenger-platform/guides/chat-extensions), so the bot can be added into 1:1 or multi-person discussions

## Design
- [ ] Messenger Template Designs, [DesignKit](https://developers.facebook.com/docs/messenger-platform/design-resources/design-kit)
  - [ ] Welcome screen
  - [ ] Survey layouts
  - [ ] [Persistent Menu](https://developers.facebook.com/docs/messenger-platform/thread-settings/persistent-menu)

## Platform Additons
- [ ] Associate with Ushahidi Messenger App Bot
  - [ ] Add to datasource UX/or new UI
  - [ ] Set/Store access token
- [ ] Expose API to receive inbound webhook events from FB
- [ ] Build a Messenger BOT
  - [ ] I would strongly suggest this bot be a sub module of platform to allow for easier data access integration, it should be a "plugin"
  - [ ] Because we are essentially constrained by FB and the API they offer/accept the bot is more or less a process of plumbing, it is relatively straightforward in and of itself. 
  - [ ] I would suggest building a basic bot soon that has the ability to:
    - [ ] Receive events
    - [ ] Read/Write Platform DB
    - [ ] Has deployment scripts

**Comment by caharding** [comment]
@willdoran @jshorland @rjmackay I updated the user story into 4 stages up above.

**Comment by willdoran** [comment]
@caharding Cool, looks good, I would be happy to help @Angamanga get setup next week to start making the basic bot if that fits with @jshorland scheduling?

**Comment by caharding** [comment]
@jshorland does that timing work for you?

**Comment by jshorland** [comment]
@charlie @willdoran @angamanga I'm starting to get concerned about the amount of work piling up in platform. Especially with this non negotiable tech debt we need to fix, minimal devs, and we are almost through April. I'm scheduling a planning meeting with @willdoran @angamanga this week to figure out how we are going to manage this.

**Comment by rjmackay** [comment]
I might be missing something but the "Simple bot" spec seems a little vague:

> User is alerted they can report on violations

I assume this is: a user can send a message to the bot and it responds letting them know they can report violations?

> We can take response to questions and rich data, this can be passed by to the platform

I have no idea what this really means?

> User is linked to Uchaguzi

When? Based on what?

**Comment by rjmackay** [comment]
FYI there are a few possible PHP modules around for powering bots: https://github.com/setkyar/laravel-messenger-bot-management
https://github.com/christophrumpel/chatbot-php-boilerplate

I'm sure there are more. That was just initial google results. But definitely worth seeing if there is existing code to speed us along

**Comment by Angamanga** [comment]
@jshorland @caharding @willdoran An update on the bot: It is still not finished to send to review so it will not be ready and reviewed for the 28th of May. Hopefully I will be able to send it to review by the end of this week. After discussion with @rjmackay  yesterday we concluded that for this first version, I'll focus on being able to report to a single facebook-survey, consisting of Title, Description, Photo and Location(if the user want to share that).   After that and after input from testers, we can add more functionality. Any thoughts / comments about that? Please ping me with more questions if you have any!

**Comment by caharding** [comment]
All good. After catching up yesterday it is clear that this is just the 1st iteration and we will deal with the more complex issues of survey mapping (required fields etc.) in the next iteration.

**Comment by Angamanga** [comment]
These are the features currently available:

- [ ]  A persistent menu situated in the bottom of the chat-window where the user can choose to read more about Uchaguzi or send a report
- [ ]  Ability to submit reports with text only or image and/or location to Uchaguzi (currently only to a specific form but there is functionality prepared to add a menu where the user can choose to which form to submit if we want that)
- [ ] If the user submits a photo, the bot asks for a report
- [ ] The bot is currently in english but when translations to Swahili is done, there is functionality to add a language-switcher
- [ ] The bot will be connected to the Uchaguzi-fb-page as soon as it is reviewed by Facebook (submission-process is started, only need logo now). If you want to test right now, please send me your facebook-login-email and I add you as a tester!

Full user flow can be found here: https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46fec5d472b780a18eeeaa59ad1dd39c2852257c3d3bf2785a90ed2d9571394d4d1f0cf31b0d0c00eef39b2ea3e23d71de5f5eeb873f5973c53d47acb88a1eb653b874995397f4edd4189fb5646fb2c99d452c1c031288fb5432a39e4bcb5df44ce84d47e9.pdf

**Comment by justinscherer** [comment]
@Angamanga Uchaguzi logo for the bot is here:
![Uchaguzilogomark 1040.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46dd9792228596b386e5b044ab50f186220676237d54e1673295f127b54778154d555ca9440c5e45a8fadc2df0e43a77895c5dedd1655e7d943f45bea4905dee5fee7fd616cfe3fe9846d2eb3c2fe68f86473b1903108bfe5937a58b06.png)

let me know if you need anything else.

**Comment by Angamanga** [comment]
@justinscherer Thanks! Nothing else right now...

**Comment by justinscherer** [comment]
logo with transparent background:
![logomark 1040 trans.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46e49b9d2c8f82bb84a9ee13f00db0803b4729606b48e13b628ae92dbc56395b4d5a4bf840590b47a9ffdf79a0b13f70dc5c0be5d0640d76922f0dbefad341eb5ee779c11ac7a4b6984fc1e23c21ee83894b371e051b8fff5e27ed.png)

**Comment by rjmackay** [comment]
@Angamanga Could you create any follow up issues for this and assign them to the bot theme/milestone? Then we should close this one out.

**Comment by Angamanga** [comment]
I have moved remaining bot-issues to the lesson-learned document for now and closing this: https://docs.google.com/document/d/190KdcA_DcikAzBP31am6xdRxe4jaaqC07atnWJnceZ8/edit
