### ISSUE TITLE
Change log of posts

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1864]
It's important to be able to keep track of logs of who has been in contact with a particular post for accountability purposes and backtracking too.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-583

**Comment by jshorland** [comment]
Simple log of who edited the post when is enough. Doesn't have to be pretty for now, but should be accessible by clicking a link on the post to view edit log.

**Comment by jshorland** [comment]
I'm going to re-open this as a more refined version of this will be necessary for Epic: tasks

**Comment by jshorland** [comment]
Permissions:
- [ ] Change log should only be visible to logged in users (not to members, or visitors)
- [ ] Manual entries can only be created by users with permission to edit posts

Any saved changes should appear in the change log automatically, indicating who changed what when (who = anonymous if author n/a)
- [ ] Post status change (created as draft, published, archived)
- [ ] Category added or removed
- [ ] Survey field edited (indicate which field was edited if possible)
- [ ] Task field edited (indicate which field was edited if possible)
- [ ] Task completed or changed back to incomplete 
- [ ] Added to or removed from collection 

Users with permission can create their own change log entries manually
- [ ] only users with the edit posts permission should see "add an entry" button
- [ ] clicking on add an entry opens long text box titled "new entry" with asterisk indicating text is required to save
- [ ] cancel option closes the box without saving
- [ ] Clicking save without any text shows error dialogue "You must enter something in the change log before you save it."
- [ ] saving with text updates the change log to reflect the new manual entry. Entry is visible to any logged in user (NOT TO MEMBERS OR VISITORS). It should show who created it and when.

**Comment by jshorland** [comment]
Designs
![change. log.png](https://zube.io/files/ushahidi/06d9636eb4b272b589e1cd3ae62194a5.png)

**Comment by willdoran** [comment]
Notes:

- On delete message warning that changelog will be deleted as well, suggest archive

**Comment by kinstelli** [comment]
Spec/Security question @jshorland 

 Regarding _Change log should only be visible to logged in users (not to members, or visitors)_, I'm wondering if there might be a situation where items that could be visible in the changelog, such as Collection names, Tag names, etc, should only be seen by admins, rather than just any logged in user.

And if so, would we want to have different log visibility that only shows certain lines to certain users?

**Comment by jshorland** [comment]
@kinstelli good nuance here. There are items that will be listed in the changelog that have permissions associated with them. They are the following:
- categories
- author (if hidden, it's only visible to ADMIN)
- parent categories (sub categories follow the parent category permissions)
- collections
- saved searches

If any of the above are set to be visible to only specific roles, these privacy settings should carry through to the changelog. 

 cc: @Angamanga @willdoran have I covered everything?

**Comment by kinstelli** [comment]
Okay, I'll have to reconsider some of the auth architecture I've used, but I'll look into this.

**Comment by kinstelli** [comment]
Separate question: I was wondering what an example changelog entry might look like for a brand new post. For automatic log entries on post updates, I'm writing a log entry for every changed field, but I assume we don't need/want that to happen for a brand new post.

**Comment by rjmackay** [comment]
We should pause this and move it into the backlog

**Comment by rowasc** [comment]
This was abandoned but there was a PR with a bunch of work done on this already. If we still want this feature to land, we should schedule it and finish it during cleanup 

commenting and assigning to myself in the meantime so I can keep track .

**Comment by Erioldoesdesign** [comment]
It seems important for deployment owners to manage large teams. I would say this is most useful if we can test/implement with a partner that has 5-10 volunteers/team members on a deployment.

Will keep an eye on this too 👁

**Comment by rowasc** [comment]
*UPDATE:*

While we may some day integrate this pending issue ( I really do want to see this deployed) , we are going to be closing the pull request for the moment to avoid having stale work in our pull request queue (it gets messy and the code is no longer easy to merge basically 😬 ). 
*However* we will retain the branch and protect it from deletion in case we do want to come back to it, that way we can find a way to integrate it :) 

CLIENT PR : https://github.com/ushahidi/platform-client/pull/815
CLIENT BRANCH: https://github.com/ushahidi/platform-client/tree/1864-changelog-client
BACKEND PR: https://github.com/ushahidi/platform/pull/2127
BACKEND BRANCH : https://github.com/ushahidi/platform/tree/1864-redo-changelog-like-tags

1864-changelog-client and 1864-redo-changelog-like-tags will be available for anyone looking to pick up this work . The ticket will remain open as it's not merged and we still want to get it done .
