### ISSUE TITLE
EPIC: Messages

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1925]
Currently, Messaging and Report Data Sources are the same things. They should be separate. 

- [ ] Admin should be able to configure all incoming messages including SMS, Email, FB
- [ ] Manager should be able to see a list of all message
- [ ] Manager should be able to sort this list 
- [ ] Manager should be able to reply to messages
- [ ] Manager should be able to turn a message into a report 
- [ ] Admin should automatically turn a message into a report based on keywords #1592 
- [ ] Manager should see messages connected to a specific post
- [ ] Manager should be able to see all messages with a specific user

Aha! Link: https://ushahiditeam.aha.io/features/PROD-551

**Comment by caharding** [comment]
Originally addressed partially in #1179
