### ISSUE TITLE
Facebook Messenger as a data source EPIC

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2082]
This Epic expands upon the original FB Bot Epic #1702. The goal is to include Facebook Messenger as a data source. The demo of this was tested live for Uchaguzi 2017. The team performed a full retrospective on the [bot](https://docs.google.com/document/d/1y6MnY3lHv7BMrPBDqT2dBHXDutwUOxbdpW9V-4_oirU/edit#) after Uchaguzi. We mapped out changes needed for 2chaguzi in #2081.

ALTERNATIVELY, we could choose to develop bots for specific sectors and resell them: elections, global health etc. This would resolve many of the design heuristic challenges of bots. Need a decision on this. 

MINIMAL BOT
- [ ] Deployer should be able to configure the Ushahidi bot with their Facebook page
- [ ] Deployer should be able to configure the welcome message to the Facebook Bot which is appended with “In a few words, describe what you would like to report.”
- [ ] Deployer should be able to set the bots default language. 
- [ ] Deployer should be alerted of any syncing errors with their bot, and given visual feedback in the app that the connection is broken. 
- [ ] After a user is greeted, they should immediately start reporting, with follow-up 
- [ ] When a user submits a report they should be able to submit video 
- [ ] The bot should automatically detect a user’s language 
- [ ] The bots text should all be translated automatically 

Needs scoping & design: 

- [ ] what additional default responses will we supply?
- [ ] what information will go into the help panel?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-518
