### ISSUE TITLE
Release v3.7.3 [ prep issue ]

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2100]
- [ ] Decide what we will send from : git log master..develop --oneline

### Platform client

- [x] 1565  - fix spacing in export modal (#767)
- [ ] updating stats to display all posts from datasources independent on data-source-filters
- [ ] relocating to timeline when user selects posts without a survey
- [ ] Rolling back d3 to 3.x because the nvd and angular-nvd3 deps do not work with 4.x
- [ ] fixing test
- [ ] changing from provider name "phone" to "sms"
- [ ] tests
- [ ] tweaking stats and filters to work with datasource-bucket-behaviour
- [ ] displaying edit only when having correct permissions
- [ ] updating language-strings #1646
- [ ] 2045 + 2044 - Fix export filters (#753)
- [ ] In webpack 2.x.x, entry is now required to be non-empty, in the short term a default value has been added.
- [ ] Flag /oauth/token requests as ignorable within interceptor
- [ ] adding markdown for survey description
- [ ] Show only my saved searches
- [ ] User ID required for collections and saved search
- [ ] User ID required for collections and saved search
- [ ] 2078 - saving the user_Id when creating a saved search
- [ ] updating tests for post-filters
- [ ] removing sources from active filters and adiding all providers to filters from the beginning
- [ ] calculating post-totals and sending correct numbers to directive
- [ ] refactoring datasource-directive and enabling checkboxes
- [ ] removing source filters from filter-modal
- [ ] WIP adding correct count to filters
- [ ] only checking enabled data-providers if logged in
- [ ] using data-source directive in mode-context-bar+removing old code #1646
- [ ] adding directive for filtering data-sources in mode-context-bar #1646
- [ ] feature: Add post source filter to the filters modal
- [ ] set authentication errors as ignorable
- [ ] Update auth interceptor tests
- [ ] Don't get a client token if a request was flagged as ignorable
- [ ] remove requirement to obtain token before sending request
- [x] Update to work with webpack 2+
- [ ] Make greenkeeper ignore platform PL
- [x] docs(readme): add Greenkeeper badge
- [x] chore(package): update dependencies

### Platform

- [ ]  Authentication/Authorization: fix header name (#2096)
- [ ]  2078 - Make user id a required field when creating a Collection or Saved search (#2079)
- [ ]  Manage posts permissions should not return true by default (#2075)
- [ ]  Added evaluation that checks columns available to see if CSV line endings are being recognized correctly. If there is a columns.9, it menas that line ending was not detected at all
- [ ]  Making my comment fit in the line limit
- [ ]  Test os9 dataset
- [ ]  947 - auto detect line endings added to CSV import
- [ ]  adding source to stats-request
- [ ]  feature: Add option to filter posts by source
- [ ]  Handle multiple values for source filter
- [ ]  Revert to failing when auth token is invalid, even if not required
- [ ]  Revert debug info in auth exceptions
- [ ]  Throw an HTTP 401 if Authorizer fails, and Auth header wasn't present
- [ ]  Allow GET requests without auth on all endpoints
- [ ]  Remove anonymous oauth token from some of the ACL tests
- [ ]  Skip oauth for collections, media, saved searches and stages too
- [ ]  cacheability: open access without authorization token to certain endpoints

- After the checklist is done, go through the release process as documented.
