### ISSUE TITLE
Epic: CSV Export Queue

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2121]
# CSV Export 2.0
Notes: 
- [ ] As *any logged in user* I want to be able to export and download large CSV files with posts/messages.
- [ ] As *any logged in user* I want to access my previous exports up to `n` days. 
- [ ] As *any logged in user* I can start an export and come back to download it when it's finished. 
- [ ] **Not supported at the moment, but cron based would be an option for those users** Using a queue is optional for users who don't need one because they have only small datasets. A warning should be thrown/shown about this somewhere so that users know the way forward if they need to do exports on queues. 
- [ ] We can use rabbit/Redis queues/ampq/whatever.  Write interfaces/abstracts with a generic design and implement them for the actual queue details as needed
- [ ] The backend  should support job confirmation and visibility timeouts

`Dev notes and checklist :`
- [ ] Add filtering support to export CLI
- [ ] Create table where we can store the export query
- [ ] Add Export Job that will work the same as notifications
- [ ] Add sed command to knit together finished files
- [ ] Update table of available files when Job finishes
- [ ] Jobs can be run by the same cron that runs the notificatons/dataprovider jobs
- [ ] Need to clean up exports every X (configurable) time

#### User requests export: 
- Note: Only logged in users will be able to export
- Step 1: User requests export. 
- Step 2: Send request. Server creates job.
- Step 3: Response : "We'll email you when the export is done"

#### Server creates CSV and sends link
- Step 1: Notify user when export is done. 
- Step 1.a: Notification will be done with email as a first step.
- Step 1.b: When available we will have a broadcast that will notify the user using the snackbar style that the export is ready and that they will get an email. (Need to link to style) 
- Step 2: User clicks on the download link and is taken to a URL where they can download the CSV. Note: This is behind authorization, no anonymous users will be allowed to download and users can't share a download link to the export from the platform.

Related tickets that we need to cover for queues
- [ ] CSV Export not working. This triggered priority assignment for the queues https://github.com/ushahidi/platform/issues/2154
- [ ] Large file download failed https://github.com/ushahidi/platform/issues/2217

**Comment by rowasc** [comment]
@willdoran this was the original queue ticket. 
I'll link everything here for sanity and tag everything

**Comment by rowasc** [comment]
@jshorland @justinscherer just adding the notes from today. 
@willdoran can you check it too? Thanks

**Comment by rowasc** [comment]
Closing as this is the epic that gave us larger exports with export history in 2018 😄
