### ISSUE TITLE
RTL (Right To Left text) not working 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2251]
This issue is also probably also a dup of #1816 

### Expected behaviour
RTL mode should work.
### Actual behaviour
RTL mode does not work at all.
### Steps to reproduce the behaviour/error
Select Arabian/any RTL language
The RTL mode is not triggered and a console error appears. 
TypeError: Cannot read property 'rtl' of undefined

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): development branch (used for sandbox/qa)

**Comment by rowasc** [comment]
@jshorland do we need to prioritize this fix for 2chaguzi?

**Comment by rjmackay** [comment]
I'm not sure what the JS errors is from.

The lack of switching is due to changes in how we added RTL styles. Previously we simply added a class. However we now generate 2 separate JS files *and* a namespace class.
The blocker for bringing fixes back to core was figuring out how to make webpack bundle both RTL and LTR css but not always load both.

I attempted to fix this in: https://github.com/ushahidi/platform-client/pull/748 but I'm not happy with that method. I think it causes all the CSS to be loaded in an inline style element. The alternative might be 2 entry points ie. rtl.html and ltr.html or something

**Comment by Angamanga** [comment]
@rjmackay Is the change in #748 the same approach that we used in fix-our-environment? Two entry points doesn't sound as bad as loading it all as an inline style-element. Could we try to do that fix now and then look at it further during our refactor? We have a todo for the js-framework research/planning that includes best-practices for styles and react and we should include this there.

**Comment by Angamanga** [comment]
I have added a pr for the rtl-fix using your old commit for this @rjmackay. It works, so one option is to use this and pay close attention to this issue when we investigate the js-framework refactor. https://github.com/ushahidi/platform-client/pull/1020

**Comment by rjmackay** [comment]
Yes  ushahidi/platform-client#748 is exactly what we did for fix-our-environment. I don't think we should take that approach - it doubles the size of the CSS we're loading (and causes a flash of unstyled content during load I think).
If its for a single deployment then yes, we could do that. But I'd really prefer we spent a little time on another approach for core.
If it works, then 2 entry points is probably fine. As long as we can figure out how to switch between them sanely.

**Comment by tuxpiper** [comment]
For upcoming cycle planning . Do we have an idea of how much time is required to fix this for good?

**Comment by rjmackay** [comment]
Landed https://github.com/ushahidi/platform-client/pull/748
but while it works in dev mode, but fails in a production build. Digging further

**Comment by rjmackay** [comment]
Turned out to be an issues with a combination of webpack plugins. See ushahidi/platform-client@bcc26c5 for details

**Comment by rjmackay** [comment]
Passed QA. Will deploy once I confirm other hotfixes are safe to deploy too

**Comment by rjmackay** [comment]
@tuxpiper @caharding RTL changes are live on ushahidi.io
