### ISSUE TITLE
Filtering by categories & surveys

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2412]
#### In mode-context-bar in map-view

- Categories can only be filtered for one survey at a time
- All other surveys get deselected when a category is selected in one survey
- A child can be selected without its parent

#### In filters dropdown
- Categories can be filtered for many surveys at a time
- Child categories can be selected without its parents

### TODO

- [ ] Test for each scenario in the test script.
- [ ] The filters drop-down  can be used to search for posts that belong to a category with no children in all surveys
- [ ] The filters drop-down  can be used to search for posts that belong to a child category  in all surveys
- [ ] The filters drop-down can be used to search for posts that belong to a survey 

# Test script (run in map and data view)

#### The mode context bar does not have categories 
It will be done in this ticket https://github.com/ushahidi/platform/issues/2435

#### The filters drop-down  can be used to search for posts that belong to a category with no children in all surveys
- [x] Add two posts that share a category. Each post should belong to a different survey
- [x] In the filters drop-down, filter for that category ONLY. 
- [x] Verify that both posts are shown in the list. 

#### The filters drop-down  can be used to search for posts that belong to a child category  in all surveys
- [x] Add two posts that share a child category. Each post should belong to a different survey
- [x] In the filters drop-down, filter for that child category ONLY. 
- [x] Verify that both posts are shown in the list. 

#### The filters drop-down can be used to search for posts that belong to a survey 
- [x] Add two posts that share a child category. Each post should belong to a different survey
- [x] In the filters drop-down, filter for that one of the surveys, let the categories remain selected (all of them) 
- [x] Verify that only posts belonging to that survey are on the list

#### The modebar can be used to search for posts that belong to a survey 
- [x] Add two posts that share a child category. Each post should belong to a different survey
- [x] In the modebar, filter for that one of the surveys, let the categories remain selected (all of them) 
- [x]  Verify that only posts belonging to that survey are on the list

#### The filters drop-down can be used to search for posts that belong to a survey and a specific category
- [x] Add two posts that share a child category. Each post should belong to a different survey
- [x] In the filters drop-down, filter for that one of the surveys, select just the category that belongs to the post in the same survey
- [x] Verify that only posts belonging to that survey  + that category are in the list

**Comment by rowasc** [comment]
Notes from @aoduor to integrate while spec'ing 
On Default permissions, recommendation:
1. If it's a child category, assign it default permissions of it's parent.
2. If it's top level, make it public ( bonus points if we can allow user to select permission on creation, but this is probably too much, lol)

Notes from Justin: we will keep the same UI, specific behavior differences to be discussed with Eriol.

**Comment by rowasc** [comment]
getting a few demos of how this works at the moment.

**Comment by Angamanga** [comment]
Behaviour-suggestion to be discussed with @aoduor and @Erioldoesdesign before decision about behaviour can made:

1. parent-categories can have less strict permission than its parents
2. child-categories can have more strict permissions than its parents, but not less strict ones
This helps if some children should be hidden and some not. 

Usecase: As a deployment-manager, I want to be able to hide some child-categories to some users but keep other child-categories visible to all users even if those children have the same parent.

**Comment by rowasc** [comment]
@Angamanga we should spec this out. `Categories can only be filtered for one survey at a time`  , we need to figure out how this fits and if it's important for CSV or not.

**Comment by rowasc** [comment]
@Angamanga I think this is it, really? 
Thoughts?

**Comment by Angamanga** [comment]
Yes, this looks good! Moving to ready for dev.

**Comment by crcommons** [comment]
@Angamanga I thought we were removing filtering from mode context bar?

**Comment by rowasc** [comment]
@crcommons we are. :/ Sorry if that's not clear.  What gave you the impression we aren't?

**Comment by rowasc** [comment]
@crcommons but we are removing CATEGORY filters, not all filters

**Comment by crcommons** [comment]
ooooh, ok. that's make sense. Just my brain being silly. sorry!

**Comment by aoduor** [comment]
> On Default permissions, recommendation:
1. If it's a child category, assign it default permissions of it's parent.
2. If it's top level, make it public ( bonus points if we can allow user to select permission on creation, but this is probably too much, lol)

Just clarifying that this was reasoning for creation of categories on the fly!

**Comment by aoduor** [comment]
@rowasc @Angamanga anything you need me to clarify here :)?

**Comment by Erioldoesdesign** [comment]
_Notes from Justin: we will keep the same UI, specific behaviour differences to be discussed with Eriol._

Anything specific you need me to answer here? I may need to see visually what happens here if it wasn't covered in Anna's demo last week

**Comment by rowasc** [comment]
@Erioldoesdesign the comment was kind of outdated since you spoke with Anna after that and we updated the description to remove the modebar categories. To confirm, we are still going ahead with removing the categories from the mode-bar, right? 

@aoduor @Erioldoesdesign also, I'm sorry you had to go through those comments, they were a bit out of date/confusing. Basically, we just needed a read of the descriptions of the issues and I didn't make that clear last Friday when I asked for a review.

**Comment by rowasc** [comment]
@Erioldoesdesign ok just saw your comment in https://github.com/ushahidi/platform/issues/2435. Confirmed. Thanks

**Comment by rowasc** [comment]
https://drive.google.com/open?id=1TFRhu5N9NCOHnuN_46h236R7nUNctv0J Demo here @jshorland

**Comment by jshorland** [comment]
so if i'm understanding the demo correctly, filters actually filter correctly now. And as I understand it, a post cannot only belong to a parent if there are children categories -- we are forcing a user to select a child if they exist under a parent?

**Comment by rowasc** [comment]
>  filters actually filter correctly now.
YUP. 
> And as I understand it, a post cannot only belong to a parent if there are children categories -- we are forcing a user to select a child if they exist under a parent?

Yes, exactly. When creating a new post, they can only select a parent if the parent does not have children. 
@jshorland

**Comment by jshorland** [comment]
Jess testing feb 14
# Test script (run in map and data view)

#### The mode context bar does not have categories 
It will be done in this ticket https://github.com/ushahidi/platform/issues/2435

#### The filters drop-down  can be used to search for posts that belong to a category with no children in all surveys
- [ ] Add two posts that share a category. Each post should belong to a different survey
- [ ] In the filters drop-down, filter for that category ONLY. 
- [ ] Verify that both posts are shown in the list. 

#### The filters drop-down  can be used to search for posts that belong to a child category  in all surveys
- [ ] Add two posts that share a child category. Each post should belong to a different survey
- [ ] In the filters drop-down, filter for that child category ONLY. 
- [ ] Verify that both posts are shown in the list. 

#### The filters drop-down can be used to search for posts that belong to a survey 
- [ ] Add two posts that share a child category. Each post should belong to a different survey
- [ ] In the filters drop-down, filter for that one of the surveys, let the categories remain selected (all of them) 
- [ ] Verify that only posts belonging to that survey are on the list

#### The modebar can be used to search for posts that belong to a survey 
- [ ] Add two posts that share a child category. Each post should belong to a different survey
- [ ] In the modebar, filter for that one of the surveys, let the categories remain selected (all of them) 
- [ ]  Verify that only posts belonging to that survey are on the list


#### The filters drop-down can be used to search for posts that belong to a survey and a specific category
- [ ] Add two posts that share a child category. Each post should belong to a different survey
- [ ] In the filters drop-down, filter for that one of the surveys, select just the category that belongs to the post in the same survey
- [ ] Verify that only posts belonging to that survey  + that category are in the list

**Comment by jshorland** [comment]
passes QA
