### ISSUE TITLE
As a deployment manager or deployment visitor, I expect to be able to download a full deployment's dataset

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2421]
This is a master issue for all backend Data export elements

Problem: CSV Export needs to work for our enterprise clients and large deployments. Right now, any export that isn’t trivial causes major issues, either being impossible to download from the client and needing someone to run a console export.

### Related issues
#2442 
  - [ ] Complete
#2443 
  - [ ] Complete
#2444 
  - [ ] Complete
#2445 
  - [ ] Complete
#2446 
  - [ ] Complete
#2447 
  - [ ] Complete
#2456 
  - [ ] Complete

### What we need for implementation [wip]

- [ ] A more reliable way to download CSVs of any size and any data density (Reference: this ticket/self)
- [ ] A way to do CSV generation without killing the servers. This includes async handling of CSV generation (queue), in chunks  (Reference: this ticket/self)
- [ ] A way to notify the user that the CSV export is being done in the background. (Reference https://github.com/ushahidi/platform/issues/2429) 
- [ ] A way to notify the user that the CSV export has been completed, in the current UI. Reference https://github.com/ushahidi/platform/issues/2428 
- [ ] A way for the user to actually download the CSV file after being notified in the UI. Reference https://github.com/ushahidi/platform/issues/2430

### TODOs for scoping
- [ ] How do we handle the actual file download? 
- [ ] How to test it? how to demo it?

### What we have to do for this feature:

- [ ] Plug exporter into our existing queue system
- [ ] Adapt and test CLI Exporter to make sure it works correctly.
- [ ] Modify Export HTTP request so that it triggers a new export job in the queue, instead of directly generating the CSV and sending it back (Make it async) 
- [ ] Implement a notification system, based on previous work with sockets+redis. (This was done for post locking and should be what we base it on)

**Comment by rowasc** [comment]
Added @willdoran to this since he has been doing the deployment setup and a ton of research that will help move this forward.

**Comment by rowasc** [comment]
Dependencies: setup xdebug in openshift so we can test in a deployment similar to prod

**Comment by rowasc** [comment]
@willdoran does this reflect what you mentioned about CSV export in the chat? Anything I should add regarding tech requirements?

**Comment by rowasc** [comment]
@willdoran sorry, another question. Do you think the subtasks are reasonable? I want to ask Eriol and Justin to link to the correct UI pieces for the notifications but want to make sure we can actually do it before

**Comment by willdoran** [comment]
@rowasc This looks good.

Yes absolutely, linking is genius.

I have two things I don't know how to link:
1. There is an existing app we made which works with redis and websockets to tell the client stuff has happened. It's built but needs some love but should be reusuable here. Do you want me to link to it or how can I best share info on it so you can decide if it's relevant?
2. Would suggest that it will also need to mirror in some parts the webhook job/cli behaviour BUT also this is a bigger scale so we need to think about what happens when a file fails, the queue should rerun just that piece that's doable but doesn't exist right now for anything.

**Comment by rowasc** [comment]
@willdoran great. 
1. Yes, please share more info on that. Share the repo too if it would help us get there faster. 
2. Agree. I'll add notes so that we tech spec this a bit more rather than just share the "WHAT" to do.

A note on process: 
This is one of the special cases I mentioned in process doc (regarding Specs DoD) where more tech details are important and should be posted and prioritized as part of the spec, IMO, since day#0 of dev time we want to have a clear idea of where to go and not be lost researching tech

**Comment by willdoran** [comment]
1. It is super simple, @tuxpiper has built redis into the deployment scripts and also this adapter but it has never been run/tested outside dev
https://github.com/ushahidi/platform-websocket-redis-adapter

2. That sounds logical, let me know how I can help.

**Comment by rowasc** [comment]
@kinstelli Mark, adding you as we discussed. I'm keeping myself assigned to be in the loop, but you can do whatever edits you feel are needed.
@willdoran as discussed, feel free to coordinate this with @kinstelli directly here

**Comment by rowasc** [comment]
@kinstelli @willdoran do we still need this ticket? do you want to drop it in favor of the sub tickets we already have, or is there some value in it?

**Comment by willdoran** [comment]
hmmm I want to keep it for now

**Comment by rowasc** [comment]
@willdoran ok . Should this go to ready for dev ?
