### ISSUE TITLE
Error in Develop-Dashboard Branch of Cloud-API

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2422]
### Expected behaviour
I should be able to log in to Dashboard on master branch

### Actual behaviour
I cannot login. I am getting this error:
Failed to load http://api.cloud.test/oauth/token: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Steps to reproduce the behaviour/error
- Switch to develop-dashboard branch of cloud-api and master of platform-dashboard
- run setup (where do I find setup instructions?)
- Attempt to login

##### Where
- [X] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by crcommons** [comment]
Closing because I'm crazy and now this is working.
