### ISSUE TITLE
[Platform API] Export Jobs should support HXL exports

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2521]
### Overview
The Export Job system should expand to support a new data type of HXL. This is essentially CSV or JSON with additional meta data in the form of HXL hashtags that have been defined for each Survey Field

## TODO

- [x] When the first chunk of a CSV is generated in an HDX export job, add row of hxl tags and attributes according to data in export_job and export_job_hxl_mapping described here https://github.com/ushahidi/platform/issues/2805
- [x] Refactor CSV Export into a usecase that we can extend to support HDX export  https://github.com/ushahidi/platform/issues/2879 
- [ ] Create usecase to support HXL Export that extends the behavior of CSV Export usecase
- [x] Exported data should follow the same rules as CSV Export, but have the extra row of tags
- [ ] The tags must be aligned correctly with the field headers (matching the user's mapping)
- [x] The file will be uploaded to the same destination as a regular CSV Export

### Requirements
- [x] Export Jobs should support additional output formats in a generic way
- [x] Export Jobs should provide metadata to Post Exporter to inform it of which output format is being used and what changes need to be made to output data

**Comment by willdoran** [comment]
@rowasc I think this needs more work. I can take a look at it, moving it backwards a step for now.

**Comment by Angamanga** [comment]
@willdoran @rowasc It looks like this is in spec? Assigning Romina and moving it to spec.
