### ISSUE TITLE
An Error label in a form should not move content out of line or break the page layout

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2556]
### Expected behavior
The error label for a field does not move content out of line.

### Actual behavior
The next field after the label looks off/moved to a side instead of being in another line
<img width="735" alt="screen shot 2018-02-28 at 10 54 03 am" src="https://user-images.githubusercontent.com/2434401/36791145-b925b6b2-1c75-11e8-8a82-5dff943d35d2.png">

### Steps to reproduce the behavior/error
Make a mistake in any field in a form (ie: while creating a survey)

### How it helps the user 
It makes forms easier to follow. Right now it can be confusing and it just looks bad. 

#### Is is ready for development when
- [x] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [x] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [x] Has all designs and UI assets available
- [x] Has all (probable) dependencies identified
- [x] Is estimated by the team
- [x] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain): EVERYWHERE

## TODO:
The error labels is found in PL-fragments: http://preview.ushahidi.com/platform-pattern-library/master/assets/html/2_fragments/#pl-pattern-messages

- [ ] Add it to a form-block and to layouts where it is used and style it appropriately to make it not move content out of place

## DEMO-SCRIPT
- [x] Go to PL-blocks, there should be one add-to-survey-block with and without an error-label
- [x] Go to http://preview.ushahidi.com/platform-pattern-library/master/assets/html/5_layouts/post-add.html, there should be an example with an error-label
- [x] Go to http://preview.ushahidi.com/platform-pattern-library/master/assets/html/5_layouts/data-edit.html, there should be an example with an  error-label
- [x] Go to http://preview.ushahidi.com/platform-pattern-library/master/assets/html/5_layouts/settings-general.html, there should be an example with an error-label

## Test script
- [ ] Go to a targeted survey
- [ ] make a mistake in any text field
- [ ] the error label shouldn't alter the layout of the fields
