### ISSUE TITLE
Update pattern library with the new Targeted Survey layout.

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2557]
#### Is is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

### TODOS:
- [ ] Add link to settings-Targeted Survey Layout to Layouts
- [ ] Add targeted survey to settings-list
- [ ] Add targeted survey-layout to settings

### DEMO-script:
- [ ] Go to http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/#pl-pattern-layout-c, there should be a link to Settings-targeted surveys
- [ ] Go to http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/settings.html, there should be a link to Targeted surveys
- [ ] Click on the link, the layout for targeted surveys should show up (and be styled according to the designs: https://xd.adobe.com/view/a9b0da01-2589-465d-ab05-db3a178d6a6f/)

**Comment by Angamanga** [comment]
@justinscherer I have a slight memory that you mentioned that the user should be able to drag and drop the questions in the wizard https://xd.adobe.com/view/a9b0da01-2589-465d-ab05-db3a178d6a6f/screen/11ae2c63-c67b-45db-b21e-8254fa572a78/New-Survey-choose-audience-targeted-2-questions-ad?fullscreen Is that correct? If so, I will add a separate issue for that, we currently don't have that functionality, it should be ok to implement but will require some more work (@middle8media correct me if I am wrong...). Also, do you know what the name of that icon is? The one with two rows of 3 dots. We don't have it already available in the PL so need to look for it.

**Comment by justinscherer** [comment]
really good point @Angamanga 

The icon is new. Iconic didn't have anything I could use and the icon for this func. is pretty standard. What formats do you need the icon in? I can drop it here. 

You're right, the draggable repositioning is a new module. Right now we have two clickable arrows that work terribly and are broken half the time.

**Comment by Angamanga** [comment]
@justinscherer png would be fine, or svg. Fantastic @middle8media added drag-drop to the PL so I will try to use it today.

**Comment by justinscherer** [comment]
We ended up just going with the grid-of-6 icon from iconic.

**Comment by Angamanga** [comment]
New tag pushed to PL (v3.7.2-rc.35)
