### ISSUE TITLE
Decide on QA process to get things to Done

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2626]
Our current QA process is not well documented. Furthermore, it is not clear how people move code from In Dev to Done through testing. 
- [ ] Decide what branches we develop on
- [ ] Decide what branches we test on 
- [ ] Decide the process of moving QAed items to master
- [ ] Decide on process of making releases
- [ ] Document this whole process

Documentation is taking place here: https://docs.google.com/document/d/1IYbo811OxoIr076eHJXYLgsL3fSGUqysQY9LaWzxZZw/edit#heading=h.v26tpw2la87e

**Comment by caharding** [comment]
@kinstelli FYI I've made this an EPIC for tracking in this cycle.

**Comment by rjmackay** [comment]
Closing. I think this is all the QA process doc now
