### ISSUE TITLE
Merge Obfuscation (formerly "Anonymization") of Reporters into Core

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2684]
### Requirements:
- [x] User can configure Hide Location per Survey
- [x] User can configure Hide Author Information per Survey
- [x] User can configure Hide Date/time per Survey
- [x] User can set a global value for the precision of locations when using Hide Location
- [x] When Hide Location is enabled, location will be only precise to a certain number of decimal places
- [x] When Author Information is hidden, the author information will not be returned from the API
- [x] When the Date/Time is hidden, the author information will not be returned from the API

### Acceptance Criteria: Site Settings
- [x] User can edit and save the precision level for hide location
- [x] When the user changes the value of the precision level the text showing the precision in terms of kilometres is updated

### Acceptance Criteria:  Survey Config
- [x] When creating/editing a Survey the User has the option to set:
  - [x] Hide Author Information
  - [x] Hide Date time
  - [x] Hide location
- [x] When Hide location is enabled for a survey, the locations should only be precise to the degree set by the global precision level under site settings
- [x] When Hide Author is enabled, the Post should display without the author information when viewing a post
- [x] When Hide Date is enabled, the Post should display without the exact time when viewing a post, it should be set to midnight of the day the post was created.

### Acceptance Criteria: Data View
- With anonymization set, go to data view
- In another tab, create a new post 
- [x] in original tab, the "1 new post" button should appear at the top of data view list
-------
- filter the list so that at least the top most post is filtered out
- [x] wait 60 seconds and confirm that the "1 new post" button does NOT appear at the top of the list
--------
- select a post mid-way down the list of posts, then refresh
- [x] the selected post should be at the top of the list
- [x] wait 60 seconds and confirm that the "new posts" button does NOT appear at the top of the list
--------
- select a post
- select a filter that will filter out the selected post
- [x] the list should refresh and the top-most post should be selected from the list
---------
- filter the list so that 0 posts match
- in another tab/window, create a new post so that it does match the filters 
- [x] back in the first tab, confirm that the new post button appears 

**How it should work?**

- Information needs to be stored in full detail in the database (just as usual)
- That’s because it needs to remain accessible to privileged users (i.e. admins)
- Users without the right privileges get anonymised data

This is tied to survey definitions and role and permissions system
- Surveys have settings for hiding information to be anonymised , by data type (i.e. "Hide exact location information")
- The "Manage posts" permission grants access to bypass the settings and see exact, non-anonymised information

The "Edit any posts" permission still allows to edit any posts, but it doesn't imply being able to access the exact, non-anonymised information.
- This allows creating a role of "unprivileged editors", who can edit non-anonymised data from posts, but still can't see (or edit) the anonymised data.

**Complications to current method**
The "unprivileged editors" role mentioned above should have a clear indication that there are fields they cannot edit.

What happens when an unprivileged editor sends an update for a post with anonymised fields.. is just that the API silently ignores any changes to the anonymised fields.

**What needs to be anonymised**
- Author information
- There is a current feature that allows hiding the author of the post, if enabled for the form. We don't need to expand on it.
- Datetime fields (metadata and custom)
- In general the client would like to drop times and leave the dates
- Times are rounded up to the top of the hour

**Location fields**
Adjust points to a grid of coarser resolution (i.e. 200m x 200m) with Circle Area instead of point on a map

**What needs to be tested**
That the anonymisation is effective:

- [x] GET /api/v3/posts
- [x] GET /api/v3/geojson
- [x] CSV download
- [x] post alerts / notifications
- [x] Web and mobile clients not breaking when we don’t send some data that could be expected

Work on this issue has been done by @rjmackay in another repo, but needs to be tested to merge

**Comment by jrtricafort** [comment]
@willdoran Do we have plans to put this behind a Feature Flag? Could we?

**Comment by willdoran** [comment]
@jrtricafort Will anon of reporters but enabled or disabled by default when it goes to prod?

**Comment by jrtricafort** [comment]
@willdoran It will be on by default.

**Comment by jrtricafort** [comment]
Confirmed w @willdoran that the current scope is sufficient.

**Comment by rowasc** [comment]
@eve this has to be tested on `qa.ushahididev.com`. 
Test the issue on both `mobile and web`  . Feel free to ask any questions that might come up here or in the slack channel with Will/myself.

**Comment by Eve-wanderi** [comment]
@rowasc  Noticed a few issues.Kindly confirm if they are valid.


1.  When i added a Post to an anyonymised Survey and i edit the Post Date. This date and Time is not anonymized as users can still see eddited dates. However this is not the case for posts which are not edited since they are rounded off.
## Please Note the Survey has been Anonymized survey used Anonymization##

![time diffrence](https://user-images.githubusercontent.com/36038029/43314483-bb98d85c-919b-11e8-9dfb-e889d560a996.png)

![image](https://user-images.githubusercontent.com/36038029/43314739-871d751e-919c-11e8-8b8c-b2db1c367c52.png)


2. What are the permissions for Edit any posts?

**Comment by willdoran** [comment]
@Eve-wanderi The data is only anonymised if the user does not have Post Edit permissions. The system checks to see if the user has permission to edit the Post if they can then they are allowed to see anonymised data.

**Comment by willdoran** [comment]
@jrtricafort This is acutally an interesting idea, we might want to create an explicit permission which controls whether or not even anyone can ever see anonymised data even if editing.

**Comment by Erioldoesdesign** [comment]
So I've looked into this from a UI perspective. I looked at:
- An input field
- Radio buttons
- Drop down

https://xd.adobe.com/view/f455f026-ce60-4549-4a8d-7118c34b9bba-8264/?fullscreen

There's 5 pages in the prototype to click through

Input field is a no, it's too complicated to figure out the increments system and I suspect would have a lot of human error.

Radio buttons is usable, accessible and works but a bit long.

Drop down is the same as radio but saves on vertical screen space. So my vote is on that one. Comments, amends and extra info I may not have considered always very welcome though! (also sorry for the delay on this one)

The main thing I'd like to make sure happens is that the copy for the 'most anonymised' and 'least anonymised' option is included. That way the users can make an informed decision using this and also if they have an understanding of km/m in relation to the data they're capturing it'll help.

**Comment by Eve-wanderi** [comment]
@willdoran this happens even for users who have not even logged into the Platform.?

**Comment by willdoran** [comment]
@Eve-wanderi I'm confused, how can they edit a post if they are not logged in?

**Comment by Eve-wanderi** [comment]
Yes they cannot edit. But when they view the edited post they can see the actual time the post was edited

Like the below screenshot i am not logged in yet when i view the post and hover on the date/time information i can see the exact time and date the post was edited.

![image](https://user-images.githubusercontent.com/36038029/43321498-b994534c-91b4-11e8-91d6-49cca49aafce.png)

**Comment by willdoran** [comment]
ah, I think I see the confusion, this feature only removes the time not the date, so they can see the date and the time however is not accurate. The time is cleared to be midnight on the correct date, so this is correct behaviour. Good catch though, thanks

**Comment by willdoran** [comment]
@Eve-wanderi I changed one of the acceptance criteria to be more specific and less unclear. Thanks

**Comment by Eve-wanderi** [comment]
@willdoran Gotcha! Yes then is works fine.

**Comment by Eve-wanderi** [comment]
@willdoran Passed QA.
