### ISSUE TITLE
Migrate settings/user/create to react

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2761]
- [ ] create new route
- [ ] create user container component and userform component
- [ ] create initial state, reducers, and actions
- [ ] create new endpoints for getting roles and posting users
- [ ] create UI tests, reducer tests, action tests, endpoint tests

Documentation:
- wiring (note that this is not reflective of new designs)
https://www.lucidchart.com/documents/edit/9e4ee737-e89e-41a1-976e-90acd9b248bc?shared=true&
- libraries
https://drive.google.com/open?id=1Lz8-qCb89EOdYsXKWlwW0tSeujCy5d5558vvdP_riJM
- state/api interactions
https://drive.google.com/open?id=1ZHCExmiDQbrdMHJAU0YJl5_HAzuBG9ZUYjK3TakPlPk

**Comment by rjmackay** [comment]
From our discussion earlier. Additional requirements
- Migrate Util class https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2959
- Create new endpoint class that doesn't use angular cache or resource.
     - This might still need to use $http via https://github.com/bcherny/ngimport to take advantage of the http interceptor for authentication

**Comment by jrtricafort** [comment]
Spoke to @crcommons . Closing this. Everything else covered by #2990
