### ISSUE TITLE
Create folder of review docs for team ahead of Montreal

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2763]
- [x] PWA Checklist
- [ ] Industry standards checklist
- [x] Dev environment setup instructions/documentation
- [x] templates for component migration
- [ ] test scripts for critical paths related to components 1-6
- [ ] order of migration
- [ ] Agenda
- [ ] Issues/tasks
- [ ] objectives

**Comment by crcommons** [comment]
https://github.com/airbnb/javascript/tree/master/react#ordering
