### ISSUE TITLE
[Platform API] User based datasource configuration for HDX

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2807]
## Acceptance criteria/Deliverable
- [ ] New endpoints listed in the ticket
- [ ] Postman collection for testing the endpoints 

## Expected behavior
- A user with access to the HDX feature should be able to configure an API Key in the new "Configure HDX API" page.
- This API Key will be saved and used only for their own HDX connections. 
- The API Key is not shared amongst other admins in the deployment and each HDX user needs their own key set up. 
- There is a way to get the API key in the backend to use it when requesting or creating data in the CKAN HDX API
- We need a new user data provider configuration that does not rely on the global `config` table . 

## Endpoints
GET /user/:id/settings
Returns the configuration for the user id

POST /user/:id/settings
Create a new setting for the user id

PUT /user/:id/settings/:settingId

Update user settings

### New table `user_settings`
id: PK
user_id: ref#user.id
config_key: string (initial entry options with group hdx: hxd.api_key, hdx.default_maintainer, hdx.default_source, hdx.default_org)
config_value: string (text)
updated: timestamp

## TASKS
- [x] Create new table
- [ ] Add create, update, list operations for user config

**Comment by rowasc** [comment]
@caharding YUP.
cc @Shadrock I understand this is the requirement. If not: then we need a per-deployment key

**Comment by Erioldoesdesign** [comment]
Can I get an update today on whether I need to look into any UI/UX design work for the configuring of the API?

So if we decide to move it to user account or webhooks or it's own settings section and if the setting up of the API requires anything (UI) that we don't have already?

This section, once in v0 will be heavily user tested to improve it for v1 but as it stands, we don't have time to test where in a deployment to place this from a user pov.

**Comment by rowasc** [comment]
@Erioldoesdesign I think this was resolved with the conversations yesterday and the new screen, but lmk if that's not the case and there are more questions

**Comment by rowasc** [comment]
@rjmackay @Erioldoesdesign burning question/suggestion: maybe we should never return the hdx api key .It's useless in the frontend and why would we do that* when we can just have a way to update it or create it instead ? 

*obviously this means we can't show it in the client.. but it's pretty common not to show api keys after you set them up. Maybe just the last 4 digits or something  like that ?

**Comment by rjmackay** [comment]
@rjmackay I like the idea of not returning the API key once set. I don't have a strong opinion on it - it'd be a neat addition though and easy enough to implement in the API

**Comment by Angamanga** [comment]
@rowasc @Erioldoesdesign Could we in some way indicate to the user that they have an api-key saved in the case we decide not to return it to the client? Otherwise I think it will be confusing.

**Comment by rowasc** [comment]
@Angamanga @Erioldoesdesign 
Yes. I think if we end up going that route, we should still return a few of the last characters (maybe ~4 or so) and make it obvious in the UI that there's an API key  so the user doesn't think "oh no, my API was not saved"

**Comment by Erioldoesdesign** [comment]
@rowasc @Angamanga So in the new screen where the user configures their API key are we suggesting that it's an empty field for the very first time a user adds in a key and then once 1 key has been added it changes to say...text like: 

'****-****-****-1234' 'change your API key'

with 'change your api key in the blue link style which would re-initialise the typeable field? this would get around some of the usability problems with users not being sure they've 'saved' the key by pressing save if they miss the snackbar.

**Comment by Erioldoesdesign** [comment]
It'd be super awesome if I can get an idea if we need what I suggested in the above comment approved and then if it needs reflecting in the design work.

**Comment by rowasc** [comment]
Yep, I love this. I think yes, reflect it in the design if possible.

**Comment by Erioldoesdesign** [comment]
It is done! Updating the prototype links now :)

**Comment by rowasc** [comment]
@willdoran @kinstelli can you review?

**Comment by willdoran** [comment]
@rowasc Approved
