### ISSUE TITLE
[Platform API] Return available HXL tags and attributes for each survey field type

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2809]
### Description: 
Endpoint that returns a list of tags and hxl attributes available for each form attribute type available. 

### Tasks
- [x] Create new tables 

Table:  `hxl_tag_attributes` => where we save which  hxl_tags are available for each form_attribute type
    - form_attribute_type: <= this is not an id. This is the type of attribute. So text field, checkbox, list, etc.  
    - hxl_tag_id: ref#hxl_tags.id

Table `hxl_tags`
   - tag_name: string
   - description: string
   - id: number

Table `hxl_attributes`
   - tag_id: ref#hxl_tags.id
   - attribute: string
   - description: string
   - id: number

- [x] Use the list at https://drive.google.com/open?id=1D0MMaEE4zYkQWpSFvbCe_779A7ORxfkw0byHRh7csAw to add the data (with a migration)
- [x] Create endpoint to provide the list to the client

Endpoint description: returns a list of tags and hxl attributes available for each form attribute type available. 

GET /hxl/form_attributes 

Response: 200 OK
```
      {
        "results": [
          {
            "form_attribute_types": ["string"], /// attribute types
            "tag_id": 0,
            "tag_name": "string",
            "tag_description": "string",
            "hxl_attributes": [
              {
                "description": "string",
                "attribute": "string",
                "id": 0
              }
            ]
          }
        ]
      }
```

### Acceptance critera:

- [ ] Provide a postman collection with an example of how to call the endpoint that follows the description of the endpoint in this ticket

**Comment by rowasc** [comment]
@willdoran @kinstelli can you review?

**Comment by willdoran** [comment]
@rowasc Should the endpoint provide search, so you can return tags by attribute type?

**Comment by rowasc** [comment]
@willdoran oh good question. I didn't add search in the spec because I don't expect we will need it for v0 as we will be pulling the full export screen with all the attributes, but I can add it quickly if you think there's a use-case for it?

**Comment by willdoran** [comment]
@rowasc Nope, sounds good. It's not hard to add when the need arises.

**Comment by willdoran** [comment]
Approved

**Comment by rowasc** [comment]
Closing, this was done  and deployed
