### ISSUE TITLE
[Platform Client] User based datasource configuration for HDX

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2813]
## Expected behavior
A user with access to the HDX feature should be able to configure an API Key in their datasource configuration. This API Key will be saved and used only for their own datasources. The API Key is not shared amongst other admins in the deployment and each HDX user needs their own key set up. 

## Notes
 
- We need a new user-dataprovider screen or module in a screen where they can add their api key. 
- This should include a link to documentation explaining how to setup the api key. 

## Concerns
- Right now datasources are at the deployment level. This means this requires a new API, somewhere to save the data, and a new way to save it in the client. Eriol is looking into the design for this. The current configuration screen at https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/9da0a49b-75d7-4486-a11f-e3acb03ed6a3/Configure-HDX-API-2/

## Backend: 
https://github.com/ushahidi/platform/issues/2807

## Todo: 
- Add a new route to this config
- Add a new controller
- Add a test-file
- Potentially, add a new endpoint (https://app.zenhub.com/workspace/o/ushahidi/platform-client/issues/1118)
- Load the api-key from new endpoint, otherwise, leave input-field blank 
- Save to new endpoint
- Add a new notification-window
- When user clicks yellow-button in the notification-window, the user is taken to the HXL-tagging-screen in data-export

 ## Demo/QA-script
This assumes the feature-flag for HDX to be ON
- Go to settings
- [x]  A new setting called "Configure HDX API" should be visible in the list
- Click on the setting
- [x] You should be moved to the settings-window. A key for the test-deployment is already saved, so you should see this screen:https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/fe471722-d17f-42e5-8f62-19cfa9e56c29/Configure-HDX-API-4
- Click on the View the guide to your API-key
- [x] https://data.humdata.org/faq should open in a new tab/window
- Click on "Change your api-key"
- You should be moved to this screen: https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/acd8beb3-1a1e-436f-b887-c27f40f617f6/Configure-HDX-API
- Click save without any api-key
- [x] An error-message should appear( https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/c46a2347-1fc6-4540-9866-af8d945d2059/Configure-HDX-API-Error?fullscreen)
- Add a api-key that is correct (found in qa-package) and save
- [x] You should be moved to this screen and a notification should be displayed https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/9da0a49b-75d7-4486-a11f-e3acb03ed6a3/Configure-HDX-API-3
- [x] The yellow "Start tagging data"-button take the user to the HXL-screen in data-export

**Comment by Angamanga** [comment]
Questions:
@Erioldoesdesign 
- is the error-message in the design correct?
https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/c46a2347-1fc6-4540-9866-af8d945d2059/Configure-HDX-API-Error?fullscreen)

**Comment by Angamanga** [comment]
@rowasc Could you please review?

**Comment by Angamanga** [comment]
@Eve-wanderi Ready for QA :)

**Comment by Eve-wanderi** [comment]
No validation error message on *first attempt* to save without Api key.

1. Click on Settings.
2. Go to Configure HDX API.
3.Click on Change your API Key.
4. Click on Save.

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/5a16b602-f626-4e96-becf-c053ba83fe9f)

**Comment by rowasc** [comment]
@Eve-wanderi this should be tested again.
