### ISSUE TITLE
[Platform API] Return HDX organizations for user

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2841]
Design ticket: https://github.com/ushahidi/platform/issues/2811
Platform client ticket:  #2840

## Tasks
- [ ] Create new endpoint
- [ ] Connect to HDX API to get the list
- [ ] Return list with only active organizations to the client

## Backend Notes: 
- To return the list of organizations a user belongs to: 
GET https://data.humdata.org/api/action/organization_list_for_user
Headers: Content-Type: application/json
Headers: Authorization: your-api-key

This will provide a JSON list of your user's organizations with
- Image
- Display name (this is what we want the client to have)
- State: Maybe only show active ones?
- Id
(and other fields)

TODO : 
- [ ] New endpoint: /hxl/:user_id/organizations will return active organizations for the user
-  GET /hxl/:user_id/organizations
    - 200
    ``` "result": {
           "organizations": [
                {
                    "display_name": "something",
                    "description": "something else", 
                    "id": "something else", 
                },
                {
                    "display_name": "something 2 ",
                    "description": "something else 2", 
                    "id": "something else", 
                }
            ]    
       }
    ```
- [ ] Add tests with mocked results that test error states such as connection failure with HDX server

Related to "Organization" field here https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/1c15cc61-5a2e-4dbe-8018-a7bd2b559d40/Data-export-CSV-landing-page-HDX-single-survey-20/?fullscreen

**Comment by rowasc** [comment]
@willdoran can you review?

**Comment by jrtricafort** [comment]
@willdoran This is no longer In Development, right?

**Comment by willdoran** [comment]
@jrtricafort It's done yep

**Comment by jrtricafort** [comment]
Cool @willdoran can you update the workboard stage?
