### ISSUE TITLE
[Platform Client] Fetch surveys+survey-fields to export for HDX

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2848]
### Description
in order to display and add tags and attributes to the survey-fields, we need to fetch the surveys from the api

### Designs
https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/?fullscreen

### Todo
*When going to the hdx-page in data-export-settings...*
- Fetch all surveys available, except targeted surveys from the api
- Fetch attributes for each survey
- Add tests to make sure surveys and attributes are loaded correctly
- Add the surveys and attributes to a table according to layout (this ticked does not include attributes/tags, just fetching and displaying the surveys)
- Add checkboxes for each field
- Also add a "select-all" button in the beginning of the table
- Add a text in the end of the table that indicates how many fields are selected

### QA-checklist
Designs: https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/9a17d59a-cdfd-4ed4-aec5-573cdfeadb97/Data-export-HDX-single-survey

Assuming HDX-feature-flag is ON
- Go to data-export-settings, click on "assign attributes and tags" button
- [x] All surveys (not targeted) and survey-fields should be visible 
- [x] No targeted surveys should be visible
- [x] There should be a select-all button, when clicking on that, all fields should become selected
- [x] There should be checkboxes in front of each survey-field
- [x] The numbers of fields selected should be the same as the count in the text in the end of the table

**Comment by jrtricafort** [comment]
I strongly recommend that we explicitly do **not** support HDX tagging for Targeted SMS, at least in the v0 scope (assuming that it adds any front-end/back-end complexity to do so).

Both features are under feature flags, and my understanding is that in the foreseeable future, the intersection of those feature flags is expected to be close to zero. 

@rowasc @Erioldoesdesign @Angamanga if you're in agreement, I think we should break out "Support HDX Tagging for Targeted Surveys" as a separate issue, and place them in the backlog to revisit later. Let me know

**Comment by rowasc** [comment]
@jrtricafort absolutely, agree that tagging targeted surveys should be out of scope at the moment

**Comment by Angamanga** [comment]
@rowasc Could you please review?

**Comment by Angamanga** [comment]
@Eve-wanderi Ready for QA :)

**Comment by Eve-wanderi** [comment]
Yes this has passed QA.
