### ISSUE TITLE
 [Platform API] Refactor CSV Export into a usecase that we can extend to support HDX export

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2879]
### TODO
- [ ] src/Console/Command/PostExporter's handle should only deal with getting params and calling the ExportPost usecase
- [ ] an ExportPost use case should be created to handle: 
    - Getting posts with correct permissions
    - Creating header rows
    - Adding columns with data
    - Running validator and formatter
    - Returning the result
- [ ] Add tests to validate the Post Exporter results

Acceptance criteria:
- [x] the post exporter works from the CLI as before 
- [x] generating a CSV without the refactor and with the refactored usecase results in the same output (minus any bugs fixed and documented of course)
- [x] the post exporter works when called with the lumen queues repo as before
- [x] usage examples are documented

### Usage: 
Call the exporter with : 
php artisan export --limit={limit} --offset={offset} --include-header={1|0} {jobid}

offset/limit : a number, the offset and limit of rows to fetch
include-header: 1 or 0 . 1 to include it, 0 to not include it. It's used to be able to generate chunks of a csv without headers and then join them later with the first chunk with header
jobId: the export job id 

#### branch in platform api
feature/2879
