### ISSUE TITLE
[ Platform API ] Setup CKAN API Client for laravel

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2880]
### TODO 
- [ ] Setup a CKAN client in Lumen to connect to the HDX CKAN API 

###  Acceptance criteria: 
- [ ] I can call a package from the HDX usecases and get/send data to ckan api
- [ ] I can configure the CKAN API url to be test-humdata.org or humdata.org depending on .env vars
- [ ] I can return a friendly error message to the client if CKAN is down

## Implementation notes
I found a few packages that are generic PHP packages. I also found this one  https://github.com/Germanaz0/laravel-ckan-api for laravel that looks nice enough to use and extend as needed. We could fork and add some tests to it instead of writing our own client. 
Good things about it:
- ready for laravel so probably won't have issues to issue in lumen
- easy to use
- has nice examples in docs file
- uses guzzle
- Small and most of its code looks testable

Bad
- no tests provided :(

**Comment by rowasc** [comment]
duplicated for some reason... closing
