### ISSUE TITLE
[ Platform API ] Setup CKAN API Client for laravel

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2881]
### TODO 
- [ ] Setup a CKAN client in Lumen to connect to the HDX CKAN API 

###  Acceptance criteria: 
- [ ] I can call a package from the HDX usecases and get/send data to ckan api
- [ ] I can configure the CKAN API url to be test-humdata.org or humdata.org depending on .env vars
- [ ] I can return a friendly error message to the client if CKAN is down

## Implementation notes
I found a few packages that are generic PHP packages. I also found this one  https://github.com/Germanaz0/laravel-ckan-api for laravel that looks nice enough to use and extend as needed. We could fork and add some tests to it instead of writing our own client. 
Good things about it:
- ready for laravel so probably won't have issues to issue in lumen
- easy to use
- has nice examples in docs file
- is being updated from time to time 
- uses guzzle
- Small and most of its code looks testable

Bad
- no tests provided :(

**Comment by rowasc** [comment]
@rjmackay is there a CKAN client you prefer? I know you looked at some but I can't remember if you liked any of them . 
I was going to just make a quick wrapper myself but this laravel one seems ok as a starting point that we could extend as needed / contribute back to

**Comment by rjmackay** [comment]
No. Basically pick something that seems stable and recently maintained

> this laravel one 

link?

**Comment by rowasc** [comment]
https://github.com/Germanaz0/laravel-ckan-api

**Comment by rowasc** [comment]
@kinstelli  @willdoran Can you review and provide any input you have?

**Comment by willdoran** [comment]
@rowasc Approve
