### ISSUE TITLE
[Platform Client] Add basic layout and exitlinks to HDX on export-screen

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2892]
### Designs
https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/9a17d59a-cdfd-4ed4-aec5-573cdfeadb97/Data-export-HDX-single-survey

### TODO:
- Add header, text and links to export-screen
- Add basic table to export-screen

### QA-checklist
*Assumes HDX-feature-flag is on*
- Go to settings->data-export->export hdx
- [ ] There should be a Heading with the text: "Assign your HXL tags and attributes and select fields to export..."
- [ ] There should be a description with the same text as in the designs
- Links should point to:
- [ ] Humanitarian Data Exchange: https://data.humdata.org/ (opens in new tab/window)
- [ ] Configure your HDX API: Route created in this issue: https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2813 (in same window)
- [ ] HXL-tag-assist: https://tools.humdata.org/examples/hxl/ (opens in new tab/window)
- [ ] HXL cheat sheet: http://hxlstandard.org/standard/1_1beta/postcards/ (opens in new tab/window)

**Comment by Angamanga** [comment]
@rowasc Could you please review?

**Comment by Angamanga** [comment]
@Eve-wanderi Ready for QA :)
