### ISSUE TITLE
Create actions and reducers for roles and users

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2992]
### Roles
- [x] create actions for roles
  - [x] action to call endpoint and handle response
  - [x] action to receive endpoint
  - [x] action to handle errors
- [x] create reducers for roles
  - [x] set initial state of
    - [x] roles array
    - [x] Boolean value for loading users
    - [x] error object
  - [x] reducer to return loading=true when roles are being fetched
  - [x] reducer to return roles and loading=false when roles are received
  - [x] reducer to return loading=false and error message when error is received

### Users
- [x] create actions for users
  - [x] action to call save user endpoint
  - [x] action to receive response from saving user
  - [x] action to handle error when saving
- [x] create reducer for users 
  - [x] initial state that has 
    - [x] users array
    - [x] error object
    - [x] loading boolean 
  - [x] reducer that returns state when we call the action that saves the user and sets loading bool to true
  - [x] reducer that adds user to users list in store and sets loading to false
  - [x] reducer than saves errors and sets loading to false

### Tests
- [x] Tests for each user reducer
- [x] Tests for each user action
- [ ] Tests for each role action
- [x] Tests for each role reducer
- [ ] mock endpoints so that we can test actions

* consider refactoring to have just a UI reducer for loading and/or errors

**Comment by crcommons** [comment]
New issue added to add tests for roles actions. moving forward.
