### ISSUE TITLE
Create COMRADES "demo"

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#3067]
## Overview
The output of this Epic will be a COMRADES deployment that is populated with data that have been processed by all of the COMRADES features and can be explored by potential users. The current COMRADES deployment and repo can be used for this purpose. There are a variety of ways that the demo could work, especially in tandem with other pieces of collateral. Such as: 

- We could have a deployment with an accompanying video tutorial or click through to explain new features. 
- It's possible that the demo deployment would either allow new posts to be entered so users could see how the services annotate the posts or, on the other hand, the demo could be created so potential users could only view posts.

### What data should be used? 
COMRADES has two, relatively complete, data sets that could be used: A subset of Uchaguzi data or a collection of Tweets from Hurricane IRMA in the U.S.

## Who is it for? Who are the users?
The demo will be for two primary users: 

1. Potential users who want to see a concrete example of how the COMRADES suite of features has added to the functionality of Ushahidi.
2. EU officials who will evaluate the COMRADES project based on this final output. 

## What privacy impacts does it have?
- This Epic does _not_ change the personal data we collect?
- This Epic should _not_ expose data that was previously private: we would, ideally, use a sub-set of the Uchaguzi data (e.g. published reports) for this. 
- Does it send data to new services? or change how we process it?
The demo _should_ send data to the existing YODIE and CREES services, but also through two new additional services that are currently in scope ([see #3057](https://github.com/ushahidi/platform/issues/3057)).

## Requirements
To be spec'd. 
### Who will this be deployed to?
This will be for the COMRADES repo/deployment. Although it is COMRADES specific, it is a very good opportunity for us to create a demo template that could be used for core v3.

### What documentation needs to change?
We will need to write some user-facing content to walk them through the demo (e.g. a sample script of what buttons to push to see specific features). Ideally, the "Read Me" page of the appropriate repo would contain clear instructions for installing the COMRADES platform; list (or link to) deeper documentation for third party services; and list or link to user-facing instructions (there are currently several issues out for COMRADES documenation (#2865, #2741, #2740),   

## Deployment

*Does this deploy new services?*
*Do the new services have health checks?*
*Can this be feature flagged and deployed disabled?*

**Comment by jrtricafort** [comment]
@willdoran Looping you in on this. Let's discuss here this week.

**Comment by jrtricafort** [comment]
Connected with Will.

Questions for @Shadrock                        
-We need clarification on what exact data should be on here. Can we decide this or is this something COMRADES decides?
-Does the deployment need to be on its own domain, or can it be something like comrades.ushahidi.com ?

Risk:
-If the data requirement comes from COMRADES and is complex (e.g. that twitter data is in a tough format) then this could balloon from a  ~1 day dev task to more

**Comment by rowasc** [comment]
@jrtricafort this should be assigned to cycle 6, right?

**Comment by jrtricafort** [comment]
Yep, added to Cycle 6

**Comment by Shadrock** [comment]
@jrtricafort here's a bit of additional detail: we should probably hop on a call to follow up. 
- Given they way things go, I would definitely expect this to balloon and take more time than we expect. If only for the simple reason that this likely requires us to _upload_ a dataset into a deployment. And based on what I'm seeing with .csv export... this is likely to be more complicated than we anticipate. 
- The deployment does _not_ need to be on its own domain, so something like comrades.ushahidi.com. Would be fine. 

The thing that's worrying me most now, in light of #3073, is the .csv issue. Creating this demo would ideally be a simple question of populating a deployment by uploading a good dataset. I may be wrong, but when looking at all the csv issues we're having I get a bit worried... So, a few more detailed thoughts on the data to be used...  
- Because COMRADES is a prototype platform, there are no deployments of it that have "real data." There have been a few test deployments used to try evaluate _some_ of the features introduced by the COMRADES project, but there hasn't been a full deployment that collects reports and uses _all_ of the tools, hence, there is no real data that shows what it can do. 
- COMRADES does have a few different, _partial_ data sets that could be run through COMRADES services - such as YODIE, and CREES - _outside of the deployment_ and then imported to the deployment but even these have problems: most notably that they are data sets culled from Twitter, which do not have accompanying geographic coordinates. Which would mean uploading the Twitter data, appended with COMRADES services, and then still processing the posts just like in a normal deployment in order to geolocate them. 
- We have also considered taking a subset of the published Uchaguzi posts (from the eventual output of #3073); running these through YODIE and CREES services (again, outside of the deployment) and then uploading these. This would seem like the obvious option, but the question I have is, will we be able to upload such a dataset and have it display correctly? I'm specifically thinking about the new fields, "Annotation from YODIE" and "CREES Automated Labeling" ([see example here](https://comrades-stg.ushahidi.com/posts/2562)).
- Which begs the question... how would a dataset have to be formatted to correctly upload into a COMRADES deployment?

**Comment by jrtricafort** [comment]
Adding clarification from Shadrock: The data import is a one-time act that we can control, not an ongoing workflow we need to support. @Shadrock will connect with Juan next week to walk through how data is exported from other COMRADES systems (CREES, YODIE), so we can begin to scope what the transformation->import step needs to look like.

**Comment by Shadrock** [comment]
Some further clarifications and update on this:
There are two "hard dates" that exist for this, with slightly different requirements for each, which I sketch out below. It's best to think of these as building upon one another, as we won't be setting up separate deployments or anything like that. 
September 24th: Harith is giving a talk at a major conference and wants to demo the platform. I'm not sure if we'll have the EMINA (#3057

**Comment by rowasc** [comment]
@Shadrock the fixes for categories being shown correctly #3244  are now deployed to comrades-stg and comrades-hdx

Veracity and Actionability are deployed and I tested both today  #3057 


Next up (TODAY)
- [ ] Check CREES/YODIE are running. Setup services.
- [ ] Run another round of tests that include all services and export to be safe and catch anything I missed this week
- [ ] Populate https://comrades-stg.ushahidi.com with some sample data (probably a handful of Uchaguzi posts) and ensure that there is a survey configured that will send a new post to all services (Shadrock could do this but may need a bit of help ensuring all services are configured correctly).
- [ ] Write docs for HDX
- [ ] Write docs for #3057

**Comment by rowasc** [comment]
@Shadrock 

Veracity and Actionability are deployed and I tested both today  #3057 
Checklist
- [x] Change maintainer id for user id in HDX
- [x] Make categories descriptions visible in category fields
- [x] Check YODIE is running.
- [ ] Check CREES is running.. (is not right now)
- [ ] Run another round of tests that include all services and export to be safe and catch anything I missed this week 
- [ ] Follow up on FB BOT issues
- [ ] Populate https://comrades-stg.ushahidi.com with some sample data (probably a handful of Uchaguzi posts) and ensure that there is a survey configured that will send a new post to all services (Shadrock could do this but may need a bit of help ensuring all services are configured correctly).
- [x] Write docs for HDX (sent draft for review to Shadrock, can continue editing tomorrow)
- [ ] Write docs for #3057 (added the configuration options for Will to review. I think the rest is covered by the webhooks docs but I can write a detailed setup doc that explains how to setup the webhooks themselves if not)

**Comment by Shadrock** [comment]
@rowasc @willdoran quick note that OU is following up on the CREES service, and there appears to be a new bug on [https://comrades-stg.ushahidi.com](https://comrades-stg.ushahidi.com). I've re-named one of the surveys but it's not showing up in map view, despite showing up as changed in the settings. 

1. I went into the settings for "Integration Survey" and changed it to "YODIE & CREES" because I want to create demo surveys that explain what services they pull from. I saved the changes and they show up fine _in the detailed survey view only_
<img width="1304" alt="1 survey issue" src="https://user-images.githubusercontent.com/4574998/45792654-eed05580-bc4b-11e8-8bfa-c7519e77c563.png">
2. However, these changes are not reflected in the view that shows all surveys: the original "Integration Survey" name remains. 
<img width="1298" alt="2 survey issue" src="https://user-images.githubusercontent.com/4574998/45792672-08719d00-bc4c-11e8-8fcd-1f1df5527d67.png">
3. And the changes also don't show up in the map view: the old survey name remains. 
<img width="1304" alt="3 survey issue" src="https://user-images.githubusercontent.com/4574998/45792786-90f03d80-bc4c-11e8-9820-ae5dda16f644.png">

**Comment by halani** [comment]
CREES service is up and running again. We informed our Systems guys to monitor the service constantly.

**Comment by rowasc** [comment]
Confirmed CREES is running again. Thank you!

**Comment by rowasc** [comment]
@Shadrock just an update that I've been trying to reproduce the cache issue today without much luck. Could you let me know what browser you were using? 
Thank you

**Comment by rowasc** [comment]
Alright. 
@Shadrock this is where we are. FBBOT is running and saving the data correctly, CREES is running. I'm going to test _everything_ again now just in case. 


Checklist
- [x] Change maintainer id for user id in HDX
- [x] Make categories descriptions visible in category fields
- [x] Check YODIE is running.
- [x] Write docs for HDX (sent draft for review to Shadrock, can continue editing tomorrow)
- [ ] Write docs for #3057 (added the configuration options for Will to review - now trying to integrate the actual setup steps)
- [x] Check CREES is running.. (is not right now)
- [ ] Run another round of tests that include all services and export to be safe and catch anything I missed this week
- [x] Follow up on FB BOT issues
- [ ] Populate https://comrades-stg.ushahidi.com with some sample data (probably a handful of Uchaguzi posts) and ensure that there is a survey configured that will send a new post to all services (Shadrock could do this but may need a bit of help ensuring all services are configured correctly).

**Comment by halani** [comment]
It appears that the results from CREES in https://comrades-stg.ushahidi.com are incorrect. Shadrock might have already raised this to be checked. I've just now checked with the CREES developer (Gregoire), we he wonders whether the problem is that the platform is calling the Uchaguzi version of CREES http://socsem.open.ac.uk/comrades/uchaguzi/ and not the main CREES services at http://socsem.open.ac.uk/comrades/events/    
Worth checking if this is indeed the case.

**Comment by rowasc** [comment]
Hi @halani . following up on this now.

I just reviewed the CREES URL is  `http://socsem.open.ac.uk/comrades/events/` in the server. 

I'll update this issue as soon as we have more information,I'm debugging this locally now

**Comment by rowasc** [comment]
@halani @Shadrock the bug in the service proxy is fixed now, _new_ posts should have the correct CREES tags and match the results from the http://socsem.open.ac.uk/comrades/events service. https://comrades-stg.ushahidi.com/posts/218 this is a new post with the tags , @halani can you confirm this lookks correct to you? 


I will re-run pre-existing posts through the service today so that they get the correct tags too.

**Comment by rowasc** [comment]
@halani can you create a new account (with your open.ac.uk or gmail account) and let me know so I upgrade you to admin in the platform?

**Comment by halani** [comment]
I've created a new account with h.alani@open.ac.uk

**Comment by rowasc** [comment]
@halani you are an admin now. You'll need to log off and login again to see the change

**Comment by halani** [comment]
yes the login works, and it's admin. The CREES labeling for https://comrades-stg.ushahidi.com/posts/218 is also correct.  many thanks. looks all great now.

**Comment by rowasc** [comment]
@halani great. Thank you ! 
I'll go re-generate the pre-existing published posts now so they get the new tags.

Let me know if anything comes up.

**Comment by rowasc** [comment]
closing since the final COMRADES report/demo was delivered
@Shadrock feel free to reopen if necessary  :)
