### ISSUE TITLE
Migrate legacy regression scripts outline to testpad

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3088]
Problem: our current regression on testpad does not include the full scope of a regression, so we need to iterate/improve upon it. 

### TODO 
Using: 
https://docs.google.com/spreadsheets/d/1jkXjNiIepHQG2vEVwfG1EHp9pNPiHCryi0qxsHUgAWA/edit#gid=1760039862

- [x] Migrate each section that are still relevant to platfrom
- [x] Add details to each specific sections(ie if it says "Add people " , add the details of how the Add people feature should work
- [x] Check back / get reviews from coordinator (Romina) so we adjust it and are ready for a full regression before lumen deployment.

**Comment by rowasc** [comment]
Moving this to "In Development" since Eve already started.

cc @Eve-wanderi
