### ISSUE TITLE
Fix int as string issue in hxl_tags endpoint

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3111]
## Overview
In the endpoint where we return all tags and attributes and the form_attributes, the hxl_attribute ids are being returned as a string (number, but represented as a string). They should be returned as numbers.

## TODO
- [ ]  Run array map to have INT values for form_attribute_ids.

## TEST SCRIPT
- [ ] Call the /hxl/tags endpoint in a deployment with hxl enabled
- [ ] You should receive a list of hxl_attribute ids represented as int, not strings

This ticket was created from #2984 as part of a set of tech debt issues we need to fix

**Comment by rowasc** [comment]
@willdoran this is a pretty silly mistake I made back in hdxv0. I think it should be a 1 pointer since we know the solution already. Thoughts?

**Comment by willdoran** [comment]
yep agree
approved
