### ISSUE TITLE
Fix int as string issue in hxl_tags endpoint

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3112]
## Overview
In the endpoint where we return all tags and attributes and the form_attributes, the hxl_attribute ids are being returned as a string (number, but represented as a string). They should be returned as numbers.

## TODO
- [ ]  Run array map to have INT values for form_attribute_ids.

## TEST SCRIPT
- [ ] Call the /hxl_tags endpoint
- [ ] You should receive a list of hxl_attribute ids represented as int, not strings
