### ISSUE TITLE
Create initial Lumen application

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3539]
**TODO**
Create an initial Lumen application and add it to the platform-voice-integration repo. The application does not need any content or extra coding right now, we just need the basic installation where we will build this application!

- [ ] Install and create a Lumen-project and connect it to a mySql-database locally on your computer (with or without Homestead, whatever works, Homestead might help but if you managed it without it before go ahead!)
- [ ] Commit the project
- [ ] Make a pull-request to the repo (ping Anna on slack if you want to share screeen and do this together).

Some useful documentation:

Lumen: https://lumen.laravel.com/docs/5.8
Homestead: https://laravel.com/docs/5.8/homestead#per-project-installation
Lumen-intro on Laracasts: https://laracasts.com/lessons/introducing-lumen
