### ISSUE TITLE
Get familiar with the users-list code

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3540]
**BACKGROUND**
The user-list is found when clicking on "Settings" and then "Users". It is the list that shows what users are present in the deployment. We will start moving over tis section over to React. The code is found here:

Directive: https://github.com/ushahidi/platform-client/blob/js-migration/app/settings/users/users.controller.js

Html-template: https://github.com/ushahidi/platform-client/blob/js-migration/app/settings/users/users.html

Tests: https://github.com/ushahidi/platform-client/blob/js-migration/test/unit/settings/users/users-controller-spec.js

**TODO**
- [ ] Start with read through the tests, this gives you an idea what the code is supposed to do
- [ ] Check the functions in the directive, console.log or step through the functionality with breakpoints in Chrome-dev-tools to get an idea what is happening when the page loads
- [ ] Try changing things and text on the page. For example exchange the users name with permission and things like that
- [ ] Figure out what smaller parts could be "isolated" from the rest of the code and be moved to React, write a list of those in this issue.
