### ISSUE TITLE
Start with moving over a little piece

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3541]
**DESCRIPTION**
As a proof of concept, lets start moving over a little piece of information to React. 

**TODO**
- [ ] Create a new branch from the js-migration-branch
- [ ] Select one of the isolated parts from the list you made in https://github.com/ushahidi/platform/issues/3540

The first step is to create the files for this part. We need a component and a test-file. Look at the https://github.com/ushahidi/platform-client/blob/js-migration/app/react/settings/users/UserList/UserAvatar.spec.jsx for test-file setup and https://github.com/ushahidi/platform-client/blob/js-migration/app/react/settings/users/UserList/UserAvatar.jsx for the component

- [ ] Create one file for the test (with .spec. between the name and the jsx)
- [ ] Create one file for the component(name + .jsx)
- [ ] Commit the files
We can pair-program on below if you want to:
- [ ] Look at the test-example and copy the setup
- [ ] Figure out what you want this component to do, what is the functionality of the component?
- [ ] Write tests in the test-file
- [ ] Run `npm run tdd:jest`, the tests should fail
- [ ] Commit the files
- [ ] Go to the component-file, look at the component-example and copy the setup
- [ ] Add the functionality
- [ ] Run `npm run tdd:jest` again, it hopefully succeeds
- [ ] Commit once it succeeds
- [ ] Repeat to cover all functionality for this component

Now we will use this component in the angular code:
- [ ] Go to https://github.com/ushahidi/platform-client/blob/js-migration/app/settings/settings.module.js
- [ ] Add your component in a the same way as UserAvatar is added
- [ ] Go to https://github.com/ushahidi/platform-client/blob/js-migration/app/settings/users/users.html and exchange the piece of code you just created in react with the react-component, like this:
<your-new-component userName={user.name}></your-new-component> 

(I added userName as example prop, you add the props you need to your component)

- [ ] Remove the old html!
- [ ] Check if it looks ok!
- [ ] Commit
- [ ] Push to platform-client repository create a pullrequest

Aha! Link: https://ushahiditeam.aha.io/features/PROD-224
