### ISSUE TITLE
Start looking through the facebook bot

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3544]
**BACKGROUND**
2 years ago we created a facebook-bot that collect messages from facebook-messenger and adds them as posts in the Platform. This is similar to voice-integration, its just that instead of receiving a voice-message, we received a text-message. Because of this, we can look at the code for the facebook-bot and get inspiration for the voice-integration.

**TODO**
- [ ] Go to the repository https://github.com/ushahidi/platform-facebook-bot (you don't need to install or download the code, just look through it)
- [ ] The most interesting code is happening here: https://github.com/ushahidi/platform-facebook-bot/blob/master/app/Services/PlatformApiService.php This is where the bot talks to the platform-api. Keep this one in mind when making the voice-integration-app talk to the platform-api
- [ ] Look around the code and get a grasp of how it is set up

Aha! Link: https://ushahiditeam.aha.io/features/PROD-222

**Comment by hyounes4560** [comment]
@rowasc @Angamanga Can I work on this task? Thanks

**Comment by Angamanga** [comment]
@hyounes4560 Sorry this is mislabeled, it is not open for the community yet.
