### ISSUE TITLE
Set up the platform api and client and create a .io deployment

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3545]
In order to talk to the platform-api from the voice-integration-platform, we need to set up the api and client locally. 
**TODO**
- [x] make sure your Platform API and Client is running on your local machine. If its not, follow the installation-instructions here: https://docs.ushahidi.com/platform-developer-documentation/getting-started/setup_alternatives/vagrant-setup (reach out to Anna or David if you get run into any problems)
- [x]  once you have the local environment set up, go to https://ushahidi.io/create?tier=demo_1 and set up a deployment on .io Select the "Demo" plan.
- [x] Reach out to David, he will help you upgrade it!
