### ISSUE TITLE
Make a http request to the platform-api

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3546]
**DESCRIPTION**
In order to create a post in the platform, we can do a http-request to the api, just as the web-client does when you create a post in the platform-web. The goal of this project is creating posts out of the voice-messages a user send, but as a first step, we want to make sure the voice-integration-app is able to communicate and create posts in the api.

**TODO**
*Preparations*
The platform can receive posts that are "structured" = belongs to a specific survey, or "unstructured" = doesn't belong to a specific survey. Unstructured posts are posts received from other datasources than the web, for example sms or email and also for the voice integration. For now, we will use an endpoint(route) that is dedicated to sms (I will create a specific endpoint for this project, but have not done it yet). In order to use this endpoint, we have to enable the datasource for sms in the platform.
- [ ] Log in to your local platform from the browser.
- [ ] Go to settings->datasources and select smssync
- [ ] Select "Accept survey submissions from this source"
- [ ] Add a "Secret" (can be any string, remember it, you will use it in the next step)
- [ ] Don't care about any of the other instructions, but take note of the "Sync-url" that is written in step 2, you will use it in the next step.
- [ ] Click "save"

*Test in Postman*
Ok, so now the preparations are done, lets test this in Postman.
- [ ] Open postman
- [ ] Create a new post-request
- [ ] Add the "sync-url" that you noted above
- [ ] In "headers", add `Content-Type: application/json`
- [ ] In "body", add the following info in the format "raw":
``` {"message": "This is where you add your message to be a post", "from":"voice integration", "type":"sms", "direction": "incoming", "status": "receive", "secret":"add your secret key in the "}```
- [ ] Click on "send" and now the message should appear in the platform in the browser if you are logged in (click on "Data" to see the incoming posts )

**Comment by Jenniline** [comment]
ok. The todos will really help on the breakdown of this task.
