### ISSUE TITLE
Practice http-requests and routing in Lumen

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3559]
**Description**
Lets practice the concept of http-requests, routing and the Lumen application structure before diving into the Platform. Lumen has a great guide for this.

**TODO**
- [ ] Download Postman
Experiment with routes in the Voice-integration-application
- [ ] Follow the examples in https://lumen.laravel.com/docs/5.8/routing and add your own routes in the application. Experiment with what you return in each route
- [ ] Test the routes in Postman (Hint: You can serve the voice-integration-application through running  `php -S localhost:8000 -t public`)
Experiment with adding controllers
- [ ] Add a controller with help of the Lumen-docs: https://lumen.laravel.com/docs/5.8/controllers
- [ ] Restructure your own routes to use the controller, instead of just returning things in the routes, make it call a function and return the same thing from the controller instead (examples in https://lumen.laravel.com/docs/5.8/controllers#basic-controllers)
- [ ] Read through the requests and response-docs for Lumen: https://lumen.laravel.com/docs/5.8/requests and https://lumen.laravel.com/docs/5.8/responses
