### ISSUE TITLE
Connect select/deselect -options on the user-toolbar

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3578]
**Description**
In order to make the "select all" and "deselect all" links to work in the user-toolbar, we can connect them with similar function as the toggleUser-function in the checkbox. When a user clicks "select all", the state-variable "selectedUsers" should contain all available user-ids, and when a user clicks "deselect all", "selectedUsers" should be an empty array.

**TODO**
- [ ] Look at the function "toggleUser" in the users.actions.js and how it is connected to users.reducers.js. Create a similar function for select/deselect all (call it for example toggleAll or similar)
- [ ] import the function in userListContainer
- [ ] send the function as a prop to userToolbar
- [ ] use the function when a user clicks on the select/deselect-buttons
- [ ] when a user clicks "select all", the toggleAll function should add all user-ids to the selectedUsers in the users-reducer.
- [ ] when a user clicks "deselect all", the toggleAll function should remove all user-ids from the selectedUsers-variable in the users-reducer.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-211

**Comment by lalidiaz** [comment]
I am Outreachy applicant, could I try to solve this? Thanks!

**Comment by Angamanga** [comment]
@lalidiaz Sorry this issue is outdated so closing it now. You can check the other tickets in the community-task, hacktoberfest and outreachy labels. Thank you!
