### ISSUE TITLE
Test our user manual - open to everyone!

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3665]
# Intro
Our user-manual is live here: https://docs.ushahidi.com/platform-user-manual/, any help with testing and trying out the user-manual is very helpful! Please help us make it better!

# Task
- If you have a Ushahidi-deployment already set up, you can use that one for testing,  otherwise, you will get a link in Slack!
- Go to https://docs.ushahidi.com/platform-user-manual/ and walk through the manual step by step.
- Take note of things that:
  - Are confusing
  - Screenshots that are outdated
  - Things that are wrong, for example instruction that does not work, or point you to the wrong place
  - Any other suggestions and comments you have. 
Write down your notes as comments in this issue.

Thank you for your time and help 🎉 🙏 🙇‍♀ !

**Comment by Obadha2** [comment]
**Outdated SMSSync section under Data Sources**
The SMSSync section of Data Sources is outdated and doesn't match the current state of the application.
Sections that are outdated include: 
- Availability of the SMSSync application - the application is not available on the PlayStore and the .apk file has to be downloaded from an external site. This needs to be reflected in the docs, including instructions on how to install a file that's downloaded outside of the official google application store.

Sections that could use improvements include:
- Screenshots are unclickable. User can't click on the included screenshots to zoom in for a closer look. We should either have images that can be clicked on and zoomed into, or images that are sufficiently zoomed into already.
- Introduction - clearer brief of what user should be able to do with this i.e "this enables you to send posts to survey through SMS" etc
- Include mobile screenshots. The only screenshots available are from the web side. Screenshots from the web side would be most useful in guiding the user, too.
- Better guidance on the application's pages, or where to find things (like Sync URL, keywords etc). Screenshots would also help best with this.

**Comment by rowasc** [comment]
@CeciliaHinga we need some help editing the docs and ensuring we apply Walter's feedback. Could you work on it this week? 
Thanks!

**Comment by anap226** [comment]
Hi @Angamanga, hi @rowasc. I am an outreachy applicant and was wondering if this could be one the first issues I could work on. Thanks

**Comment by Angamanga** [comment]
@anap226 Thank you for your interest in contributing! Please go ahead with this issue :)

**Comment by amycruz97** [comment]
can i help with this also

**Comment by blossom-babs** [comment]
Hello, @Angamanga I am an outreachy applicant. Can I work on this too?

**Comment by Annysah** [comment]
Hello, I'm Anisat Akinbani an Outrreachy applicant. 
Can I work on this issue?

**Comment by Angamanga** [comment]
@blossom-babs @Annysah @amycruz97 Thank you! This ticket is mainly about checking out the docs and reporting issues with it so everyone can participate 🎉. Please go ahead!

**Comment by amycruz97** [comment]
the issues we should report is it going to be focused on accessibility

**Comment by ulomau** [comment]
@Angamanga hi, please i am an Outreachy intern looking for issues to work on. Please can i join and work on this issue? Thank you

**Comment by ulomau** [comment]
Hello @Angamanga and @rowasc  my name is Uloma,  an Outreachy intern. I worked on this "Ushahidi platform user-manual documentation" to make it more accessible to users so that the guide can help every user achieve its  objective which is a guide to user manual installation.
I took my time to go through the installation guide and picked out all the grammar mistakes and effected  corrections to them. I changed some text and grammar structures to make it better, readable and give the user the instructions needed. I corrected punctuations as well. 

I noticed the the URL provided under the topic "Something Seems Wrong?" can not be reached.
### Something seems wrong?
~~~
If something doesn't seem to work we suggest giving a try to open your deployment website address, but adding a "/verifier" at the end of it.
For instance, if the address of your deployment is https://ushahidi.example.com , we suggest you to try to open: https://ushahidi.example.com**/verifier**
~~~


The corrections are many so i will not paste the corrections to avoid clustering this editor, i will paste the page URL here.... 

https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/platform_release_install#installation-overview

My corrections is this text  below...

Please do let me know if there is any more thing needed.


### **[API & Client] Bundle release install**

### Installation Overview


Welcome to Ushahidi platform user-manual installation. We recommend that you install the latest release.

If you're a developer and you want to extend the use of Ushahidi platform or contribute to our code, kindly follow the development installation instructions in https://github.com/ushahidi/platform/blob/develop/README.md

### Installing the latest release

The Ushahidi user platform release bundles are pre-built compressed files, which do not require further building or downloading. The files for the release bundles are available on the platform-release repository in Github. The files are named ushahidi-platorm-release-vX.Y.Z.tar.gz .

If you are in a shared hosting solution and you are not sure if it supports Ushahidi, you should check with your provider for the requirements.

The installation procedure will vary depending on your setup, but the requirements in all cases are the same


- PHP 7.2 or 7.3.

- A web server that supports PHP. This can be apache 2 or nginx.

- PHP invokable from command line

- The following PHP modules installed:

   

- [ ] curl

  

- [ ]  json

  

- [ ]  mcrypt

  

- [ ]  mysqli

 

 - [ ] pdo

   

- [ ] pdo_mysql

    

- [ ] imap

   

- [ ] gd

- A MySQL database server: these instructions assume that you know how to create a database in your MySQL server and obtain user credentials with access to such a database.

The instructions and example commands are written specifically for Debian Linux or a derivative of it (Ubuntu, Mint, etc). You may have to adjust some things if you are installing on a different flavour of Linux, or a different OS.

### Apache 2 with mod_php

- Ensure mod_rewrite is installed and enabled in your apache server.

- Copy into your document root the contents of the html/ folder after unzipping the Ushahidi-platform-release-v4.X.Y.tar.gz bundle file.

- The dist/ folder contains the suggested configurations for the virtual host (apache-vhost.conf). The configs are default, you just need to ensure that there is an "AllowOverride" directive set to "All" for your document root (where the app has been unzipped).

- Create a platform/.env file. This file will contain your database credentials and other important configurations.

 

- Use the following command line below as a guide. Lines that start with the character # are comments and you do not need to copy them.

~~~
DB_HOST=<address of your MySQL server>
DB_DATABASE=<name of the database in your server>
DB_USERNAME=<user to connect to the database>
DB_PASSWORD=<password to connect to the database>
DB_TYPE=MySQLi

APP_ENV=local
APP_DEBUG=false
# It is encouraged you create your own APP_KEY , it MUST be 32 characters long! 
APP_KEY=SomeRandomKey!!!SomeRandomKey!!!
# This is only relevant for debug level stuff like timestamps in log messages
APP_TIMEZONE=UTC

CACHE_DRIVER=array
# See comments down in the doc for other options
QUEUE_DRIVER=sync
~~~


- Run the database migrations and execute this command from the platform folder:

  

- [ ] `php artisan migrate`



- Ensure that the folders logs, cache, media/uploads under platform/application are all owned by the user that the webserver is running on.

  

- [ ] i.e. in Debian derived Linux distributions, this user is www-data, belonging to group www-data, so you would run: `chown -R www-data:www-data platform/storage/{logs,app,framework}`

- Generate the secret key required to secure the user authentication subsystem (passport):

  

- [ ] `php artisan passport:keys`

Set up the cron jobs for tasks like receiving reports and sending e-mail messages.

You'll need to know which user your web server is running as. We'll assume the Debian standard www-data here. Run the command crontab -u www-data -e and ensure the following lines are present in the crontab:

~~~
MAILTO=<your email address for system alerts>
*/5 * * * * cd <your document root>/platform && php ./artisan datasource:outgoing >> /dev/null
*/5 * * * * cd <your document root>/platform && php ./artisan datasource:incoming >> /dev/null
*/5 * * * * cd <your document root>/platform && php ./artisan savedsearch:sync >> /dev/null
*/5 * * * * cd <your document root>/platform && php ./artisan notification:queue >> /dev/null
*/5 * * * * cd <your document root>/platform && php ./artisan webhook:send >> /dev/null
~~~

Restart your apache web server and access your virtual host. You should see your website and be able to login with the credentials:
user name: admin
password: admin

~~~
Make sure to log in at least once. The system will ask you right away to provide a valid e-mail address (that will override the "admin" user name).
That's also a great chance to set a more secure password. 🔐👍
~~~

### nginx with php-fpm

This procedure is pretty similar to the one detailed for apache above, but has the following exceptions.

- Step 1: mod_rewrite is specific for Apache, in nginx the module is named ngx_http_rewrite_module. It is usually included and enabled.

- Step 2: instead of configuring Apache, you will need to configure nginx.

- Step 3:To configure nginx, see the example of nginx-site.conf in the dist folder. You would usually drop this file in a place where it is included from the main configuration file. It assumes php-fpm is listening on port 9000 of the localhost.

- Step 4: To configure nginx, see the example of nginx-site.conf in the dist folder. You would usually drop this file in a place where it's included from the main configuration file. It assumes php-fpm is listening in port 9000 of the localhost.The default php-fpm configuration should work. 

- Step 5: Most importantly, you need to ensure that the listed directives match with the fastcgi_pass directive in the nginx host configuration file.

- Step 6: Once you are done, restart both your nginx and php-fpm services.


### Shared hosting (Cpanel, Dreamhost, Bluehost, etc)

In general, the instructions for Apache can be taken as a guideline.
Each shared hosting provider comes with their own set of particularities, so we can only provide general directions here.
In all cases, you'll need to ensure to:

- Decompress the release file and place the contents of the `html` folder in the Webroot of your shared hosting domain or subdomain.

- Create a database for your website and write the access details in the `platform/.env` file (as per step 4 of Apache 2 instructions).

- You must have command line access (SSH) to run the ` php artisan migrate` and other `artisan` commands as outlined above.

- Most importantly, a URL rewriting mechanism has to be in place, so that requests to /platform/api/v3/ _are to be forwarded to the `index.php` script inside `platform/httpdocs` . When invoking that script, the "api/v3/*" part of the url should be passed to the script into the a `$_SERVER` or environment variable. If your host uses Apache and supports .htaccess_ files, most of this should be taken care of for you.

### Something seems wrong?

In a situation where something doesn't seem to work right, we suggest for you to give a try at opening your deployment website address, but adding a "/verifier" at the end of it.
~~~
For instance, if the address of your deployment is https://ushahidi.example.com/ we suggest for you to try and open: https://ushahidi.example.com**/verifier** 
~~~
The latest releases of the Ushahidi Platform comes with a little handy tool called "https://docs.ushahidi.com/platform-developer-documentation/development-and-code/installation-helper" which is started by accessing that specific address in the deployment.

If something is wrong, this tool may provide you with useful pieces of information about what exactly seems to be the cause of the problem.

### Connecting the mobile app

Please note that the mobile app relies on the contents of the "config.json" file to connect to the API backend.

To help the app find the backend, ensure that the key `backend_url` in the JSON file is set appropriately to the absolute public URL of your deployment (i.e.  `"backend_url": "https://example.deployment.com" ` ).

If you are running the Docker container, you can set the variable using the SITE_URL environment variable. (In the default, install the site URL as the backend URL).

### Queue drivers (and "sync" driver issues)

The Ushahidi Platform API uses a queue system for running some end-user requested operations in the background. At the time of this write up, such operations are CSV for importing and exporting. More may come up in the future.

The challenge during installation is that queue systems usually take additional set up, and by using the "sync" queue driver as a first option, we are removing the need for that additional set up. This is not magic but a compromise, because there will be effectively no queue: the jobs will run synchronously, right away, when the request is made by the user.


The problem with asynchronous set up is that the long-running operations (imagine, creating a CSV with thousands of rows) can take a long time, and the web server may throw a timeout before the operation is complete.

If you run into these problems, you will need the additional setup detailed in this section.

### Redis

If you can install Redis, we would recommend that you enable cache, as it will allow you to enable caching through it.

In this case, get Redis installed (do not forget the `Php-redis` extension in your web server host), and modify the following queues in the `platform/.env` file:

~~~
CACHE_DRIVER=redis
QUEUE_DRIVER=redis
REDIS_HOST=localhost  # or other host, if running separately
REDIS_PORT=6379       # or other port, if your installation required that
~~~


### Can't do Redis ...
If Redis is not available for you, you could give a shot to the `database` driver, which will use the database to keep track of the jobs. This may be less ideal in high traffic installations but should work well otherwise.

In that case, change this entry in the `platform/.env` file:

~~~
QUEUE_DRIVER=database
~~~

And run the following commands (from your `platform` folder):

~~~
php artisan queue:table
php artisan migrate
~~~

### Queue workers
Great! So jobs will be sent over to Redis or the database, instead of holding up the web server responses. But who does the work these jobs entail? You need queue workers.

The main challenge is to keep them working when you are not looking. We will document two possibilities here:
You can install / configure a system process supervisor
Examples of process supervisors are systemd, upstart, pm2 , supervisord or chaperone.

Here we'll document how to configure http://supervisord.org/ , which is one of the popular options. 
You would need to add the following block to your http://supervisord.org/ configurations, (usually found under `/etc/supervisor` and `/etc/supervisor/conf.d`

~~~
[program:ushahidi-platform-workers]
process_name=%(program_name)s_%(process_num)02d
command=php <your document root>/platform/artisan queue:listen --sleep=3 --tries=3 --timeout=290
autostart=true
autorestart=true
user=www-data    # !! this only works for debian/ubuntu systems
numprocs=2       # you can increase this for more workers
redirect_stderr=true
stdout_logfile=<your document root>/platform/storage/logs/worker.log
~~~

Then the following command makes sure workers are started if they haven't started already:

~~~
sudo supervisorctl reread
sudo supervisorctl update
sudo supervisorctl start ushahidi-platform-workers:*
~~~


If you check your running processes (i.e. with the `ps -ef` ) you should see some processes with names similar to  `artisan queue:work` 
You can not install or configure anything system related, but you've got cron.
If you can't set up a process supervisor, you may still have old trusty cron available.
The idea here is that you can set up a cron job, to wake up your queue workers every few minutes, get their job done and go back to sleep until the next interval comes.

This can be done by adding the following line to your crontab (interval of 10 minutes):

~~~
*/10 * * * * cd <your document root>/platform && php ./artisan queue:work --stop-when-empty
~~~

You may adjust the interval to be shorter. In extreme cases with lots of jobs, your worker processes may pile up if the interval is too short.

For more material on this topic, see this document from the https://laravel.com/docs/5.8/queues project documentation website.

**Comment by treasurechristain** [comment]
@Angamanga I'm Amadikwa Joy N. An outreachy Applicant. Can I work on this issue please.

**Comment by Angamanga** [comment]
@treasurechristain Yes, please go ahead :)

**Comment by treasurechristain** [comment]
After Going through the Manual, I must say its really awesome and straight forward.
But I think these area needs some modifications

You mentioned three plans 
![threeplans1](https://user-images.githubusercontent.com/20610726/96050067-eff6ff80-0e70-11eb-9338-cae8b542c25d.PNG)

But I saw only two plans after clicking on the link attached to it
![threeplans2](https://user-images.githubusercontent.com/20610726/96050236-2f255080-0e71-11eb-8ee4-eeb9f3e460cd.PNG)


I think you should change this from _**Human rights abuses**_ to **Human rights abuse**
![humanrightabuse](https://user-images.githubusercontent.com/20610726/96050457-904d2400-0e71-11eb-87c8-85021e093e68.PNG)

Under  _**Survey**_ the image of **Add survey is not there**
![survey1](https://user-images.githubusercontent.com/20610726/96051234-fab29400-0e72-11eb-8cc8-c7ec128ace31.PNG)

Rather I saw only **Edit Survey**
![survey1old](https://user-images.githubusercontent.com/20610726/96051322-2afa3280-0e73-11eb-95a0-cf6c8bd3f0cc.PNG)


**My Suggestion:**

I suggest you remove excess bullet points here
![removethedot](https://user-images.githubusercontent.com/20610726/96050595-cd191b00-0e71-11eb-8635-5ded1d89abc1.PNG)

I suggest you set the alignment of the text to  **_Justify format_**
![justifythepage](https://user-images.githubusercontent.com/20610726/96050711-0487c780-0e72-11eb-872e-3cbb073f8ada.PNG)

**Comment by treasurechristain** [comment]
@Angamanga Those are my findings, hope it will be helpful.

**Comment by Angamanga** [comment]
@treasurechristain Thank you! This is very useful, we'll review shortly! 🙏

**Comment by mariehposa** [comment]
Hi @Angamanga, Can I work on this too?

**Comment by bukolabisuga** [comment]
Hi @Angamanga, the user manual is really great but I found a few areas that need modification. 

**Suggestion 1:**
To improve accessibility and readability, I suggest that these points should be numbered so the user knows that they are two different options:
![image](https://user-images.githubusercontent.com/28568830/97056563-33dcb980-1581-11eb-85cd-985bd4e2c61b.png)

**Suggestion 2:**
This image of the error message should be much bolder for the user to see:
![image](https://user-images.githubusercontent.com/28568830/97056863-e3b22700-1581-11eb-89c1-7e21177e0dbd.png)

Thank you.

**Comment by Angamanga** [comment]
@bukolabisuga Thank you! 🙏

**Comment by rene-saenz** [comment]
Hello! I saw this marked as a good first issue and wanted to make my first contribution. Unfortunately, this guide seems to be mostly accurate to the material. The one note I have is that the use of _**Bold Italics**_ should be more judicious to increase readability. The overuse of emphasis makes the page more noisy and reduces the usefulness of emphasis. It seems that bold italics are used for quoted phrases, but this may be replaceable by simple bolding or bolding in combination with quotation marks. I hesitate to be more prescriptive, as it is a style choice after all.

**Comment by Razeetech** [comment]
Good Morning,  am an outreachy applicant and i would like to contribute to this project

**Comment by MugoBrian** [comment]
> # Intro
> Our user-manual is live here: https://docs.ushahidi.com/ushahidi-platform-user-manual/, any help with testing and trying out the user-manual is very helpful! Please help us make it better!
> 
> # Task
> * If you have a Ushahidi-deployment already set up, you can use that one for testing,  otherwise, you will get a link in Slack!
> * Go to the https://docs.ushahidi.com/ushahidi-platform-user-manual/ and walk through the manual step by step.
> * Take note of things that:
>   
>   * Are confusing
>   * Screenshots that are outdated
>   * Things that are wrong, for example instruction that does not work, or point you to the wrong place
>   * Any other suggestions and comments you have.
>     Write down your notes as comments in this issue.
> 
> Thank you for your time and help 🎉 🙏 🙇‍♀ !
> 
> Aha! Link: https://ushahiditeam.aha.io/features/PROD-186

Hello @Angamanga. When I click on the link to the user-manual it redirects me to this page (see the screenshot below).

![Screenshot from 2024-03-05 17-51-54](https://github.com/ushahidi/platform/assets/49617104/c4a8a0bb-caba-46ab-b062-93c6c7f852b6)

Kindly confirm on your end, or perhaps I need administrative access?

**Comment by Angamanga** [comment]
Hi @MugoBrian! Sorry about that! Try this link instead: https://docs.ushahidi.com/platform-user-manual/

**Comment by MugoBrian** [comment]
Thank you.It works!

**Comment by MugoBrian** [comment]
Hello @Angamanga. Below are my findings:

1. **Suggestions**
In the list of Live Developer chat rooms, there should be a Discord link, and remove Skype (since it's not popularly used)

2. **Incorrect Links**
Under the About Ushahidi section (see screenshot below).

The impact report link is incorrect
![Image](https://github.com/ushahidi/platform/assets/49617104/d7bb1445-0cbf-4aec-ab98-3ecbb2664dd8)

Under [Mzima] Ushahidi Platform User Manual (see screenshot below)

- The contribution guide link is incorrect, it's returning a 404 page in the docs.
-  The IRC link is redirecting to a wrong site.

![Image](https://github.com/ushahidi/platform/assets/49617104/0222a00c-430a-4134-96b1-5dfc9ba1e8e6)

3. **Things that are wrong**
Under 3.1 Accessing your deployment > 3.1.1 Log in (see screenshot below)
In the note the Username is not supported as an input for login.

![Image](https://github.com/ushahidi/platform/assets/49617104/62e271be-5bda-471e-a9d1-de88b53b20e1)

**Comment by DivineAbbah** [comment]
Hello @Angamanga , I took a test to trying out the user manual and here are some things I found.

 On the  "About Ushahidi" page, I clicked on the Impact report link and while on the page, Clicked on the Strategy button and saw that it has a picture metric of UShahidi goals stating "Last Updated May 31, 2023"
See Screenshot below:

![Image](https://github.com/ushahidi/platform/assets/118902914/716c49b4-8b7c-4ddd-9192-de6252bdb2a0)

**Comment by JO-YE** [comment]
Hello @Angamanga, these are some of the issues I found out while going through the manual:

### Contribution Guide Link directed to 'Page not found'

- ![Image](https://github.com/ushahidi/platform/assets/111038087/f55882e6-b0f7-4f56-bef2-44172e22fab2)
- ![Image](https://github.com/ushahidi/platform/assets/111038087/8ca295f4-9413-4470-94f5-f2f4f42f8576)

### Outdated Screenshot
The screenshot provided for '[Navigating the Ushahidi Platform User Manual](https://docs.ushahidi.com/platform-user-manual/navigating-the-ushahidi-platform-user-manual)' is not the same as what I got.

- Overview not included
- User Manual now labeled **MAIN**

#### What was provided
![Outdated](https://github.com/ushahidi/platform/assets/111038087/4aa8cc0a-67f4-4362-8c0d-f76ac2470e80)

#### What we have right now
![Image](https://github.com/ushahidi/platform/assets/111038087/f6a02ce1-18ea-40ad-9c98-ae5cfa84c0d1)

**Comment by Perpy-del** [comment]
# Ushahidi Manual
## Introduction

I would like to show appreciation to the Ushahidi team for taking out time to setup this maual. It is vast and very obvious that care was taken to ensure that users understand the Ushahidi platform using this vast manual. Here are a few things I noticed:

- ### The very first page [Mzima] Ushahidi Platform User Manual section:
   -  **Chat Feature:**
      There is the part where you ask readers to reach out if they need further guidance or asked questions

       ![Image](https://github.com/ushahidi/platform/assets/81020670/d15cc44f-6261-481c-8d57-b0941ad353ed)

       The Chat Feature link leads directly to the homepage without notifying the reader where the Chat icon is, which is at 
       the bottom right corner of the Hero Section of the homepage. It would be a little more helpful id the chat box pop 
       up once the reader clicks the link.

    - **The IRC link:**

       ![Image](https://github.com/ushahidi/platform/assets/81020670/65caa984-aefe-4189-93d4-ee00fc8e0b51)

       The link that is supposed to redirect the reader to the IRC page, at the time of this report is not reachable. Kindly 
       confirm that the link used works properly.

    - **The Contribution Guide:**
      
       ![Image](https://github.com/ushahidi/platform/assets/81020670/3391807c-31c9-4539-a21b-e905143a2dca)
       
       As at the time of this report, the Contribution guide link as displayed above, is not reachable. Kindly confirm that the 
       link used works properly.

- ### Surveys Section:
  Under *Chapter 3.3 Surveys*, there is a part that has a link that is supposed to redirect the reader to Chapter 3.3.2. 
  However, at the time of writing this report, the link redirects the reader to the [Gitbook page] 
  (https://app.gitbook.com/o/-LEUwSacjzjxNiZTJzCs/s/-LEUwT7jCr-dMz6opcAJ/3.-configuring-your-deployment/3.3- 
  surveys#3-3-2-configuring-surveys) instead of [Chapter 3.3.2](https://docs.ushahidi.com/platform-user-manual/3.- 
  configuring-your-deployment/3.3-surveys#id-3.3.2-translating-surveys). Please confirm that it is the right link that is 
  being used.
  
  ![Image](https://github.com/ushahidi/platform/assets/81020670/10b01310-ea6e-40f6-a6c5-bc5ecf15e21c)

- ### Viewing Posts
  In *Chapter 6.1 (Viewing Posts)*, for consistency, the part that asks the reader to head to Chapter 5, we could add a link 
  for consistency that redirects the reader to Chapter 5 of the manual.

  ![Image](https://github.com/ushahidi/platform/assets/81020670/3e332c8e-87e7-4773-a2ef-b015c229f283)

- ### Chapter 7 and Chapter 8 Navigation:
  Under *Chapter 7*, from *Chapter 7.1 (Saved Searches)*, the Chapter that follows it is 8.1.1, 8.1.2, etc, rather than 7.1.1, 
  7.1.2, etc., same for 7.2, the Chapters that follow are 8.2.1, 8.2.2, rather than 7.2.1, 7.2.2, etc. This has created a 
  redirection error. When you head over to *Chapter 8 (Additional Links)*, the navigation link that takes you to the next 
  page, redirects you back to 7.1, that has 8.1.1 under it, instead of ending the manual altogether. Pictures are shown 
  below for more clarification.

  ![Image](https://github.com/ushahidi/platform/assets/81020670/b767c840-e5aa-4241-ae81-57e90c7456c9

  ![Image](https://github.com/ushahidi/platform/assets/81020670/c80e7724-9521-4ec7-9c4a-f032252cdbe6)

  ![Image](https://github.com/ushahidi/platform/assets/81020670/6aa5ab2e-c158-49e1-bc11-6069718bd7ea)

It would be a great opportunity to be assigned the tasks to fix these minor issues.

**Comment by Chiemezuo** [comment]
# Introduction
This is a comment about my findings using the Ushahidi user manual from start to finish.

## User Manual [First Page](https://docs.ushahidi.com/platform-user-manual/)
It was simple and straight to the point, however, I noticed the following issues:
- There doesn't seem to be a chat feature on the homepage (contrary to the instruction), and the `IRC` link doesn't work. See the screenshot below

![Image](https://github.com/ushahidi/platform/assets/29470516/bec0150b-7841-46e6-99da-6c4e5905001a)
- There also doesn't seem to be a contribution guide

![Image](https://github.com/ushahidi/platform/assets/29470516/2a21bd6a-8704-42db-9c4d-488233b26dba)


## Navigating the Manual [Second Page](https://docs.ushahidi.com/platform-user-manual/navigating-the-ushahidi-platform-user-manual)
The picture on the screen looks to be from an earlier prototype of the page and doesn't quite reflect what the current state of the page might look to a user.

## About Ushahidi [Third Page](https://docs.ushahidi.com/platform-user-manual/about-ushahidi)
- In the **Global Mission** section, the sentences could be grammatically tweaked a little. They could be paraphrased entirely, but I think that would be better suited for an overall document revamp. 

> **For example** : People around the world need a way to share their **'voices'** during critical situations, to ask for and generate support, and to bring transparency to their issues. At the same time, organizations and governments lack understanding of what is happening on **ground**; they need a way to make sense of how to respond effectively and quickly. See the screenshot below.

![Image](https://github.com/ushahidi/platform/assets/29470516/3c9b5c78-ae65-43fd-92dd-34ff5cabba78)

- The links to the impact report don't seem to work.

- In the screenshot below, I feel that it's a perfect opportunity to share links to those open-source projects. It might help with funding (if needed) or more contributors.

![Image](https://github.com/ushahidi/platform/assets/29470516/6f02753b-a064-4c5d-bf05-1c6c1d834536)

## Overview [Fourth Page](https://docs.ushahidi.com/platform-user-manual/overview-of-ushahidi-platform-v3.0)
This page is quite spot on.

## Technical Specifications [Fifth Page](https://docs.ushahidi.com/platform-user-manual/overview-of-ushahidi-platform-v3.0/technical-specifications)
Also very spot on.

## Installing Ushahidi Platform [Sixth Page](https://docs.ushahidi.com/platform-user-manual/1.-installing-ushahidi)
I don't think the following section should be added since there's no information on how to do it yet. It could be a future addition. Docs should only ideally contain current (or past) information.

![Image](https://github.com/ushahidi/platform/assets/29470516/7f8ba769-61fc-4c99-b289-b50791d040a0)

## Setting up the deployment [Seventh Page](https://docs.ushahidi.com/platform-user-manual/2.-setting-up-a-deployment)
I appreciate the level of detail that went in here.

## Summary of other sections
The other sections have very small issues that do not need to be in their own separate sections.

- In the section for managing people on deployments, both for [roles](https://docs.ushahidi.com/platform-user-manual/4.-managing-people-on-your-deployment/4.1-roles) and [users](https://docs.ushahidi.com/platform-user-manual/4.-managing-people-on-your-deployment/4.2-users), the 'Video coming soon' seems to have been there for some time. I think something should be done about that.

- There's a site-wide issue of images not having alt text. Seeing as there's an Outreachy project on Accessibility ongoing, the user manual is something that some grace can be extended towards.

## Conclusion
Overall, it was an extremely useful guide, and even the small fixes I suggested don't get in the way of their usability.
A great and thorough job by the team.
