### ISSUE TITLE
Role Fixes CheckList

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#4196]
**Categories**
- [x] Create a category
- [x] Set and save visibilities
- [x] Add category to survey
- [x] Log in as unprivileged user
- [x] Check categories fields presented as set
- [x] Submit response to survey
- [x] Categories selected in survey response persist
- [x] Edit category
- [x] Check edits and changes to categories persist

**Collections**
- [x] Create collection, setting permissions
- [x] Open collection to edit. Edits are saved
- [x] Add posts to collection as admin
- [x] Open collection to view posts
- [x] View collection as unprivileged user, see appropriate posts

**Saved Searches**
- [x] Create/save search
- [x] As privileged user, saved search is applied
- [x] Log in as unprivileged user, see saved search present
- [x] As unprivileged user, selecting a save search applies it

**Comment by Angamanga** [comment]
@Obadha2 Can I close this?
