### ISSUE TITLE
Integration with Web monetization - Call for Donations

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4283]
## Overview
Ushahidi Platform deployers should be able to insert a call for donations in their deployment website. The donations can be made effective using Web Monetization ( https://webmonetization.org/ )

## Who is it for? Who are the users?
Mainly activists that could use some funds to support their activities.

## What privacy impacts does it have?
- Does it change the personal data we collect?
Largely no. Users may submit pictures of themselves or their group as part of their "Calling for Donations" material, but it's expected this to be public. Other data such as ILP pointers are mean to be public and are not strongly linked to a person (it's easy to get a new one)

- Does it expose data that was previously private?
No.

- Does it send data to new services? or change how we process it?
No, not directly at least. It integrates in the browser with monetization plugins such as Coil, which rely on counting "time on site". Platform doesn't have such data.

- If privacy impacts are high risk, consider completing an impact assessment per GDPR (https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/accountability-and-governance/data-protection-impact-assessments/)

## Requirements

- [ ] Configurable "Call for Donations" content in the website.
- [ ] Configurable ILP payment pointer for Web Monetization
- [ ] Integration with Web Monetization providers (Coil) so visitors reward the deployment owner through spending time on the deployment site.
  - This requires visitors to install a plugin (Coil)
  - Mobile browser support for Web Monetization is known not to be good at the moment

### Who will this be deployed to?
Initially, deployers we know who are interested when we offer them the feature. Open source deployers who decide to enable it. 

The feature flag is "donation".

### What documentation needs to change?
User manual.

### Who will test this?
QA , support officer

### Where will this be deployed and tested?
https://grant4web.staging.ush.zone/

## Deployment

*Does this deploy new services?*
No.

*Do the new services have health checks?*
No.

*Can this be feature flagged and deployed disabled?*
Yes, it's deployed disabled. Feature flag "donation"
